export interface VideoData {
  id: string;
  title: string;
  desc: string;
  link: string;
  views: number;
  likes: number;
  dislikes: number;
  comments: number;
  status: 'active' | 'deactived';
  createdAt: string;
}

export interface UserData {
  id: string;
  email: string;
  nickname: string;
  profileImageUrl: string;
  status:
    | 'ACTIVE'
    | 'DEACTIVATED'
    | 'SUSPENDED_7'
    | 'SUSPENDED_15'
    | 'SUSPENDED_30';
  banReason?: string;
  createdAt: string;
}

export const MOCK_CONTENTS: VideoData[] = [
  {
    id: '1',
    title: '2026 신년 해돋이 명소 베스트 10',
    desc: '전국에서 가장 아름다운 일출을 볼 수 있는 장소를 소개합니다.',
    link: 'https://example.com/video/1',
    views: 15000,
    likes: 1200,
    dislikes: 12,
    comments: 57,
    status: 'active',
    createdAt: '2026-01-01',
  },
  {
    id: '2',
    title: '초보자를 위한 리액트 넥스트JS 완벽 가이드',
    desc: 'App Router부터 서버 컴포넌트까지 한 번에 정리해 드립니다.',
    link: 'https://example.com/video/2',
    views: 8250,
    likes: 850,
    dislikes: 5,
    comments: 124,
    status: 'active',
    createdAt: '2026-01-05',
  },
  {
    id: '3',
    title: '겨울철 실내 운동 루틴 20분',
    desc: '층간소음 없이 집에서 할 수 있는 전신 유산소 운동입니다.',
    link: 'https://example.com/video/3',
    views: 21048,
    likes: 3400,
    dislikes: 45,
    comments: 89,
    status: 'deactived',
    createdAt: '2026-01-10',
  },
  {
    id: '4',
    title: '에어프라이어로 만드는 겉바속촉 통삼겹',
    desc: '실패 없는 에어프라이어 요리 꿀팁 대방출!',
    link: 'https://example.com/video/4',
    views: 45187,
    likes: 5200,
    dislikes: 28,
    comments: 310,
    status: 'active',
    createdAt: '2026-01-12',
  },
  {
    id: '5',
    title: '제주도 한 달 살기 비용 총정리',
    desc: '숙소, 식비, 렌트카까지 실제 지출 내역을 공개합니다.',
    link: 'https://example.com/video/5',
    views: 12474,
    likes: 980,
    dislikes: 10,
    comments: 76,
    status: 'active',
    createdAt: '2026-01-15',
  },
  {
    id: '6',
    title: '아이패드 프로 7세대 솔직 리뷰',
    desc: 'M4 칩 성능은 과연 체감이 될까요? 2주간 써본 후기.',
    link: 'https://example.com/video/6',
    views: 9841,
    likes: 720,
    dislikes: 15,
    comments: 42,
    status: 'deactived',
    createdAt: '2026-01-18',
  },
  {
    id: '7',
    title: '자취생 필수 갓성비 주방템 추천',
    desc: '삶의 질을 수직 상승시켜주는 저렴한 꿀템들.',
    link: 'https://example.com/video/7',
    views: 33457,
    likes: 4100,
    dislikes: 33,
    comments: 156,
    status: 'active',
    createdAt: '2026-01-20',
  },
  {
    id: '8',
    title: '2026년 주식 시장 전망과 유망 종목',
    desc: '전문가가 분석하는 올해의 투자 트렌드와 포인트.',
    link: 'https://example.com/video/8',
    views: 5587,
    likes: 310,
    dislikes: 8,
    comments: 29,
    status: 'active',
    createdAt: '2026-01-22',
  },
  {
    id: '9',
    title: '반려견과 함께 가기 좋은 애견 동반 카페',
    desc: '서울 근교 드라이브 코스와 함께 추천하는 핫플레이스.',
    link: 'https://example.com/video/9',
    views: 7114,
    likes: 640,
    dislikes: 2,
    comments: 51,
    status: 'active',
    createdAt: '2026-01-25',
  },
  {
    id: '10',
    title: '미니멀리즘 인테리어 비포 에프터',
    desc: '맥시멀리스트의 방이 어떻게 바뀌었을까요? 룸투어 시작!',
    link: 'https://example.com/video/10',
    views: 19544,
    likes: 2800,
    dislikes: 19,
    comments: 94,
    status: 'deactived',
    createdAt: '2026-01-28',
  },
  {
    id: '11',
    title: '퇴근 후 10분 만에 만드는 원팬 파스타',
    desc: '설거지 걱정 없는 초간단 요리 레시피입니다.',
    link: 'https://example.com/video/11',
    views: 24884,
    likes: 3900,
    dislikes: 40,
    comments: 112,
    status: 'active',
    createdAt: '2026-02-01',
  },
  {
    id: '12',
    title: '영어 회화 독학으로 정복하는 법',
    desc: '학원 안 다니고 미드로만 공부해서 프리토킹 된 비결.',
    link: 'https://example.com/video/12',
    views: 41974,
    likes: 6200,
    dislikes: 55,
    comments: 432,
    status: 'active',
    createdAt: '2026-02-03',
  },
  {
    id: '13',
    title: '일본 도쿄 3박 4일 여행 브이로그',
    desc: '시부야, 신주쿠 맛집 투어와 디즈니랜드 방문기.',
    link: 'https://example.com/video/13',
    views: 17454,
    likes: 1500,
    dislikes: 22,
    comments: 88,
    status: 'active',
    createdAt: '2026-02-05',
  },
  {
    id: '14',
    title: '사회초년생을 위한 연말정산 가이드',
    desc: '모르면 손해 보는 세금 공제 혜택 총정리.',
    link: 'https://example.com/video/14',
    views: 6245,
    likes: 480,
    dislikes: 4,
    comments: 37,
    status: 'active',
    createdAt: '2026-02-07',
  },
  {
    id: '15',
    title: '집에서 키우기 쉬운 공기정화 식물',
    desc: "식물을 처음 키워보는 '식집사' 분들을 위한 추천 리스트.",
    link: 'https://example.com/video/15',
    views: 8594,
    likes: 920,
    dislikes: 6,
    comments: 63,
    status: 'deactived',
    createdAt: '2026-02-10',
  },
  {
    id: '16',
    title: '가성비 좋은 노이즈 캔슬링 헤드폰 TOP 5',
    desc: '10만원대 이하에서 최고의 음질과 소음 차단을 보여주는 제품.',
    link: 'https://example.com/video/16',
    views: 11234,
    likes: 870,
    dislikes: 14,
    comments: 59,
    status: 'active',
    createdAt: '2026-02-12',
  },
  {
    id: '17',
    title: '명상으로 스트레스 관리하는 5가지 방법',
    desc: '불안함을 줄이고 집중력을 높여주는 데일리 명상법.',
    link: 'https://example.com/video/17',
    views: 4844,
    likes: 540,
    dislikes: 3,
    comments: 24,
    status: 'active',
    createdAt: '2026-02-15',
  },
  {
    id: '18',
    title: '캠핑 초보를 위한 텐트 피칭 노하우',
    desc: '혼자서도 10분 만에 텐트 치는 꿀팁 공유합니다.',
    link: 'https://example.com/video/18',
    views: 13111,
    likes: 1100,
    dislikes: 18,
    comments: 47,
    status: 'active',
    createdAt: '2026-02-18',
  },
  {
    id: '19',
    title: 'ChatGPT를 활용한 업무 자동화 비법',
    desc: '엑셀 함수부터 이메일 작성까지 AI로 생산성 높이기.',
    link: 'https://example.com/video/19',
    views: 27445,
    likes: 4300,
    dislikes: 31,
    comments: 188,
    status: 'active',
    createdAt: '2026-02-20',
  },
  {
    id: '20',
    title: '향수 입문자를 위한 계절별 향수 추천',
    desc: '살구향부터 우디한 향까지 호불호 없는 베스트 셀러들.',
    link: 'https://example.com/video/20',
    views: 9240,
    likes: 810,
    dislikes: 9,
    comments: 55,
    status: 'deactived',
    createdAt: '2026-02-22',
  },
];

export const mockUsers: UserData[] = [
  {
    id: 'u1',
    email: 'alice@example.com',
    nickname: 'AliceInWonder',
    profileImageUrl: 'https://picsum.photos/200?random=1',
    status: 'ACTIVE',
    createdAt: '2026-01-15',
  },
  {
    id: 'u2',
    email: 'bob@example.com',
    nickname: 'BobBuilder',
    profileImageUrl: 'https://picsum.photos/200?random=2',
    status: 'ACTIVE',
    createdAt: '2026-01-18',
  },
  {
    id: 'u3',
    email: 'charlie@example.com',
    nickname: 'Chuck',
    profileImageUrl: 'https://picsum.photos/200?random=3',
    status: 'DEACTIVATED',
    banReason: '정지 사유사유사유입니다',
    createdAt: '2026-01-20',
  },
  {
    id: 'u4',
    email: 'dana@example.com',
    nickname: 'DanaSky',
    profileImageUrl: 'https://picsum.photos/200?random=4',
    status: 'SUSPENDED_7',
    banReason: '정지 사유사유사유입니다',
    createdAt: '2026-01-22',
  },
  {
    id: 'u5',
    email: 'evan@example.com',
    nickname: 'EvanFlow',
    profileImageUrl: 'https://picsum.photos/200?random=5',
    status: 'ACTIVE',
    createdAt: '2026-01-25',
  },
  {
    id: 'u6',
    email: 'fiona@example.com',
    nickname: 'PrincessFi',
    profileImageUrl: 'https://picsum.photos/200?random=6',
    status: 'ACTIVE',
    createdAt: '2026-01-28',
  },
  {
    id: 'u7',
    email: 'george@example.com',
    nickname: 'CuriousGeo',
    profileImageUrl: 'https://picsum.photos/200?random=7',
    status: 'SUSPENDED_7',
    banReason: '정지 사유사유사유입니다',
    createdAt: '2026-02-01',
  },
  {
    id: 'u8',
    email: 'hannah@example.com',
    nickname: 'HanBan',
    profileImageUrl: 'https://picsum.photos/200?random=8',
    status: 'ACTIVE',
    createdAt: '2026-02-03',
  },
  {
    id: 'u9',
    email: 'ian@example.com',
    nickname: 'IanZero',
    profileImageUrl: 'https://picsum.photos/200?random=9',
    status: 'ACTIVE',
    createdAt: '2026-02-05',
  },
  {
    id: 'u10',
    email: 'julia@example.com',
    nickname: 'Jewels',
    profileImageUrl: 'https://picsum.photos/200?random=10',
    status: 'SUSPENDED_15',
    banReason: '정지 사유사유사유입니다',
    createdAt: '2026-02-07',
  },
  {
    id: 'u11',
    email: 'kevin@example.com',
    nickname: 'KevKev',
    profileImageUrl: 'https://picsum.photos/200?random=11',
    status: 'ACTIVE',
    createdAt: '2026-02-10',
  },
  {
    id: 'u12',
    email: 'lara@example.com',
    nickname: 'LaraCraft',
    profileImageUrl: 'https://picsum.photos/200?random=12',
    status: 'SUSPENDED_30',
    banReason: '정지 사유사유사유입니다',
    createdAt: '2026-02-12',
  },
  {
    id: 'u13',
    email: 'mike@example.com',
    nickname: 'MagicMike',
    profileImageUrl: 'https://picsum.photos/200?random=13',
    status: 'ACTIVE',
    createdAt: '2026-02-14',
  },
  {
    id: 'u14',
    email: 'nina@example.com',
    nickname: 'NinaNine',
    profileImageUrl: 'https://picsum.photos/200?random=14',
    status: 'SUSPENDED_30',
    banReason: '정지 사유사유사유입니다',
    createdAt: '2026-02-16',
  },
  {
    id: 'u15',
    email: 'oscar@example.com',
    nickname: 'Ozzie',
    profileImageUrl: 'https://picsum.photos/200?random=15',
    status: 'ACTIVE',
    createdAt: '2026-02-18',
  },
  {
    id: 'u16',
    email: 'paul@example.com',
    nickname: 'Paulie',
    profileImageUrl: 'https://picsum.photos/200?random=16',
    status: 'ACTIVE',
    createdAt: '2026-02-20',
  },
  {
    id: 'u17',
    email: 'quinn@example.com',
    nickname: 'QuinnBee',
    profileImageUrl: 'https://picsum.photos/200?random=17',
    status: 'SUSPENDED_15',
    banReason: '정지 사유사유사유입니다',
    createdAt: '2026-02-21',
  },
  {
    id: 'u18',
    email: 'rose@example.com',
    nickname: 'Rosebud',
    profileImageUrl: 'https://picsum.photos/200?random=18',
    status: 'ACTIVE',
    createdAt: '2026-02-22',
  },
  {
    id: 'u19',
    email: 'steve@example.com',
    nickname: 'SteveJobs',
    profileImageUrl: 'https://picsum.photos/200?random=19',
    status: 'ACTIVE',
    createdAt: '2026-02-23',
  },
  {
    id: 'u20',
    email: 'tina@example.com',
    nickname: 'TeenyTina',
    profileImageUrl: 'https://picsum.photos/200?random=20',
    status: 'SUSPENDED_7',
    banReason: '정지 사유사유사유입니다',
    createdAt: '2026-02-24',
  },
];
