/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type { GetBookmarkRankingParams } from ".././model";

import { customMutator } from "../../lib/mutator";

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Redis에 캐싱된 북마크 개수를 기준으로 가장 인기 있는 영상들의 랭킹 리스트를 반환합니다.
 * @summary 실시간 인기 영상 랭킹 조회
 */
export type getBookmarkRankingResponse200 = {
  data: Blob;
  status: 200;
};

export type getBookmarkRankingResponseSuccess =
  getBookmarkRankingResponse200 & {
    headers: Headers;
  };
export type getBookmarkRankingResponse = getBookmarkRankingResponseSuccess;

export const getGetBookmarkRankingUrl = (params?: GetBookmarkRankingParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/ranking?${stringifiedParams}`
    : `/api/v1/ranking`;
};

export const getBookmarkRanking = async (
  params?: GetBookmarkRankingParams,
  options?: RequestInit,
): Promise<getBookmarkRankingResponse> => {
  return customMutator<getBookmarkRankingResponse>(
    getGetBookmarkRankingUrl(params),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getGetBookmarkRankingQueryKey = (
  params?: GetBookmarkRankingParams,
) => {
  return [`/api/v1/ranking`, ...(params ? [params] : [])] as const;
};

export const getGetBookmarkRankingQueryOptions = <
  TData = Awaited<ReturnType<typeof getBookmarkRanking>>,
  TError = unknown,
>(
  params?: GetBookmarkRankingParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getBookmarkRanking>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customMutator>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetBookmarkRankingQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getBookmarkRanking>>
  > = ({ signal }) => getBookmarkRanking(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getBookmarkRanking>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetBookmarkRankingQueryResult = NonNullable<
  Awaited<ReturnType<typeof getBookmarkRanking>>
>;
export type GetBookmarkRankingQueryError = unknown;

export function useGetBookmarkRanking<
  TData = Awaited<ReturnType<typeof getBookmarkRanking>>,
  TError = unknown,
>(
  params: undefined | GetBookmarkRankingParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getBookmarkRanking>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBookmarkRanking>>,
          TError,
          Awaited<ReturnType<typeof getBookmarkRanking>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customMutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetBookmarkRanking<
  TData = Awaited<ReturnType<typeof getBookmarkRanking>>,
  TError = unknown,
>(
  params?: GetBookmarkRankingParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getBookmarkRanking>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBookmarkRanking>>,
          TError,
          Awaited<ReturnType<typeof getBookmarkRanking>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetBookmarkRanking<
  TData = Awaited<ReturnType<typeof getBookmarkRanking>>,
  TError = unknown,
>(
  params?: GetBookmarkRankingParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getBookmarkRanking>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 실시간 인기 영상 랭킹 조회
 */

export function useGetBookmarkRanking<
  TData = Awaited<ReturnType<typeof getBookmarkRanking>>,
  TError = unknown,
>(
  params?: GetBookmarkRankingParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getBookmarkRanking>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetBookmarkRankingQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
