/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  RegisterRequest
} from '.././model';


type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;




export type getMySubscriptionResponse200 = {
  data: Blob
  status: 200
}

export type getMySubscriptionResponseSuccess = (getMySubscriptionResponse200) & {
  headers: Headers;
};
;

export type getMySubscriptionResponse = (getMySubscriptionResponseSuccess)

export const getGetMySubscriptionUrl = () => {


  

  return `/api/v1/uplus/subscription`
}

export const getMySubscription = async ( options?: RequestInit): Promise<getMySubscriptionResponse> => {
  
  const res = await fetch(getGetMySubscriptionUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getMySubscriptionResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getMySubscriptionResponse
}
  




export const getGetMySubscriptionQueryKey = () => {
    return [
    `/api/v1/uplus/subscription`
    ] as const;
    }

    
export const getGetMySubscriptionQueryOptions = <TData = Awaited<ReturnType<typeof getMySubscription>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMySubscription>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMySubscriptionQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMySubscription>>> = ({ signal }) => getMySubscription({ signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMySubscription>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMySubscriptionQueryResult = NonNullable<Awaited<ReturnType<typeof getMySubscription>>>
export type GetMySubscriptionQueryError = unknown


export function useGetMySubscription<TData = Awaited<ReturnType<typeof getMySubscription>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMySubscription>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMySubscription>>,
          TError,
          Awaited<ReturnType<typeof getMySubscription>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMySubscription<TData = Awaited<ReturnType<typeof getMySubscription>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMySubscription>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMySubscription>>,
          TError,
          Awaited<ReturnType<typeof getMySubscription>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMySubscription<TData = Awaited<ReturnType<typeof getMySubscription>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMySubscription>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetMySubscription<TData = Awaited<ReturnType<typeof getMySubscription>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMySubscription>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMySubscriptionQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export type registerResponse200 = {
  data: Blob
  status: 200
}

export type registerResponseSuccess = (registerResponse200) & {
  headers: Headers;
};
;

export type registerResponse = (registerResponseSuccess)

export const getRegisterUrl = () => {


  

  return `/api/v1/uplus/subscription`
}

export const register = async (registerRequest: RegisterRequest, options?: RequestInit): Promise<registerResponse> => {
  
  const res = await fetch(getRegisterUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      registerRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: registerResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as registerResponse
}
  



export const getRegisterMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof register>>, TError,{data: RegisterRequest}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof register>>, TError,{data: RegisterRequest}, TContext> => {

const mutationKey = ['register'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof register>>, {data: RegisterRequest}> = (props) => {
          const {data} = props ?? {};

          return  register(data,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type RegisterMutationResult = NonNullable<Awaited<ReturnType<typeof register>>>
    export type RegisterMutationBody = RegisterRequest
    export type RegisterMutationError = unknown

    export const useRegister = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof register>>, TError,{data: RegisterRequest}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof register>>,
        TError,
        {data: RegisterRequest},
        TContext
      > => {
      return useMutation(getRegisterMutationOptions(options), queryClient);
    }
    export type deactivateResponse200 = {
  data: Blob
  status: 200
}

export type deactivateResponseSuccess = (deactivateResponse200) & {
  headers: Headers;
};
;

export type deactivateResponse = (deactivateResponseSuccess)

export const getDeactivateUrl = () => {


  

  return `/api/v1/uplus/subscription`
}

export const deactivate = async ( options?: RequestInit): Promise<deactivateResponse> => {
  
  const res = await fetch(getDeactivateUrl(),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: deactivateResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deactivateResponse
}
  



export const getDeactivateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deactivate>>, TError,void, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof deactivate>>, TError,void, TContext> => {

const mutationKey = ['deactivate'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deactivate>>, void> = () => {
          

          return  deactivate(fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeactivateMutationResult = NonNullable<Awaited<ReturnType<typeof deactivate>>>
    
    export type DeactivateMutationError = unknown

    export const useDeactivate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deactivate>>, TError,void, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deactivate>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getDeactivateMutationOptions(options), queryClient);
    }
    export type syncPlanResponse200 = {
  data: Blob
  status: 200
}

export type syncPlanResponseSuccess = (syncPlanResponse200) & {
  headers: Headers;
};
;

export type syncPlanResponse = (syncPlanResponseSuccess)

export const getSyncPlanUrl = () => {


  

  return `/api/v1/uplus/subscription/plan`
}

export const syncPlan = async ( options?: RequestInit): Promise<syncPlanResponse> => {
  
  const res = await fetch(getSyncPlanUrl(),
  {      
    ...options,
    method: 'PATCH'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: syncPlanResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as syncPlanResponse
}
  



export const getSyncPlanMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof syncPlan>>, TError,void, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof syncPlan>>, TError,void, TContext> => {

const mutationKey = ['syncPlan'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof syncPlan>>, void> = () => {
          

          return  syncPlan(fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type SyncPlanMutationResult = NonNullable<Awaited<ReturnType<typeof syncPlan>>>
    
    export type SyncPlanMutationError = unknown

    export const useSyncPlan = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof syncPlan>>, TError,void, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof syncPlan>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getSyncPlanMutationOptions(options), queryClient);
    }
    export type getPlansResponse200 = {
  data: Blob
  status: 200
}

export type getPlansResponseSuccess = (getPlansResponse200) & {
  headers: Headers;
};
;

export type getPlansResponse = (getPlansResponseSuccess)

export const getGetPlansUrl = () => {


  

  return `/api/v1/uplus/plans`
}

export const getPlans = async ( options?: RequestInit): Promise<getPlansResponse> => {
  
  const res = await fetch(getGetPlansUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getPlansResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getPlansResponse
}
  




export const getGetPlansQueryKey = () => {
    return [
    `/api/v1/uplus/plans`
    ] as const;
    }

    
export const getGetPlansQueryOptions = <TData = Awaited<ReturnType<typeof getPlans>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPlans>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPlansQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPlans>>> = ({ signal }) => getPlans({ signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPlans>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPlansQueryResult = NonNullable<Awaited<ReturnType<typeof getPlans>>>
export type GetPlansQueryError = unknown


export function useGetPlans<TData = Awaited<ReturnType<typeof getPlans>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPlans>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPlans>>,
          TError,
          Awaited<ReturnType<typeof getPlans>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPlans<TData = Awaited<ReturnType<typeof getPlans>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPlans>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPlans>>,
          TError,
          Awaited<ReturnType<typeof getPlans>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPlans<TData = Awaited<ReturnType<typeof getPlans>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPlans>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetPlans<TData = Awaited<ReturnType<typeof getPlans>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPlans>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetPlansQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export type getDiscountHistoryResponse200 = {
  data: Blob
  status: 200
}

export type getDiscountHistoryResponseSuccess = (getDiscountHistoryResponse200) & {
  headers: Headers;
};
;

export type getDiscountHistoryResponse = (getDiscountHistoryResponseSuccess)

export const getGetDiscountHistoryUrl = () => {


  

  return `/api/v1/uplus/discount/history`
}

export const getDiscountHistory = async ( options?: RequestInit): Promise<getDiscountHistoryResponse> => {
  
  const res = await fetch(getGetDiscountHistoryUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getDiscountHistoryResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getDiscountHistoryResponse
}
  




export const getGetDiscountHistoryQueryKey = () => {
    return [
    `/api/v1/uplus/discount/history`
    ] as const;
    }

    
export const getGetDiscountHistoryQueryOptions = <TData = Awaited<ReturnType<typeof getDiscountHistory>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDiscountHistory>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetDiscountHistoryQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getDiscountHistory>>> = ({ signal }) => getDiscountHistory({ signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getDiscountHistory>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetDiscountHistoryQueryResult = NonNullable<Awaited<ReturnType<typeof getDiscountHistory>>>
export type GetDiscountHistoryQueryError = unknown


export function useGetDiscountHistory<TData = Awaited<ReturnType<typeof getDiscountHistory>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDiscountHistory>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDiscountHistory>>,
          TError,
          Awaited<ReturnType<typeof getDiscountHistory>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDiscountHistory<TData = Awaited<ReturnType<typeof getDiscountHistory>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDiscountHistory>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDiscountHistory>>,
          TError,
          Awaited<ReturnType<typeof getDiscountHistory>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDiscountHistory<TData = Awaited<ReturnType<typeof getDiscountHistory>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDiscountHistory>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetDiscountHistory<TData = Awaited<ReturnType<typeof getDiscountHistory>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDiscountHistory>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetDiscountHistoryQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




