/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AutocompleteParams,
  SearchVideosParams
} from '.././model';


type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;




export type searchVideosResponse200 = {
  data: Blob
  status: 200
}

export type searchVideosResponseSuccess = (searchVideosResponse200) & {
  headers: Headers;
};
;

export type searchVideosResponse = (searchVideosResponseSuccess)

export const getSearchVideosUrl = (params?: SearchVideosParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/search?${stringifiedParams}` : `/api/v1/search`
}

export const searchVideos = async (params?: SearchVideosParams, options?: RequestInit): Promise<searchVideosResponse> => {
  
  const res = await fetch(getSearchVideosUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: searchVideosResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as searchVideosResponse
}
  




export const getSearchVideosQueryKey = (params?: SearchVideosParams,) => {
    return [
    `/api/v1/search`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getSearchVideosQueryOptions = <TData = Awaited<ReturnType<typeof searchVideos>>, TError = unknown>(params?: SearchVideosParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchVideos>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSearchVideosQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof searchVideos>>> = ({ signal }) => searchVideos(params, { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof searchVideos>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SearchVideosQueryResult = NonNullable<Awaited<ReturnType<typeof searchVideos>>>
export type SearchVideosQueryError = unknown


export function useSearchVideos<TData = Awaited<ReturnType<typeof searchVideos>>, TError = unknown>(
 params: undefined |  SearchVideosParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchVideos>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchVideos>>,
          TError,
          Awaited<ReturnType<typeof searchVideos>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchVideos<TData = Awaited<ReturnType<typeof searchVideos>>, TError = unknown>(
 params?: SearchVideosParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchVideos>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchVideos>>,
          TError,
          Awaited<ReturnType<typeof searchVideos>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchVideos<TData = Awaited<ReturnType<typeof searchVideos>>, TError = unknown>(
 params?: SearchVideosParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchVideos>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useSearchVideos<TData = Awaited<ReturnType<typeof searchVideos>>, TError = unknown>(
 params?: SearchVideosParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchVideos>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSearchVideosQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export type autocompleteResponse200 = {
  data: Blob
  status: 200
}

export type autocompleteResponseSuccess = (autocompleteResponse200) & {
  headers: Headers;
};
;

export type autocompleteResponse = (autocompleteResponseSuccess)

export const getAutocompleteUrl = (params: AutocompleteParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/search/autocomplete?${stringifiedParams}` : `/api/v1/search/autocomplete`
}

export const autocomplete = async (params: AutocompleteParams, options?: RequestInit): Promise<autocompleteResponse> => {
  
  const res = await fetch(getAutocompleteUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: autocompleteResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as autocompleteResponse
}
  




export const getAutocompleteQueryKey = (params?: AutocompleteParams,) => {
    return [
    `/api/v1/search/autocomplete`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getAutocompleteQueryOptions = <TData = Awaited<ReturnType<typeof autocomplete>>, TError = unknown>(params: AutocompleteParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof autocomplete>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAutocompleteQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof autocomplete>>> = ({ signal }) => autocomplete(params, { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof autocomplete>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AutocompleteQueryResult = NonNullable<Awaited<ReturnType<typeof autocomplete>>>
export type AutocompleteQueryError = unknown


export function useAutocomplete<TData = Awaited<ReturnType<typeof autocomplete>>, TError = unknown>(
 params: AutocompleteParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof autocomplete>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof autocomplete>>,
          TError,
          Awaited<ReturnType<typeof autocomplete>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAutocomplete<TData = Awaited<ReturnType<typeof autocomplete>>, TError = unknown>(
 params: AutocompleteParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof autocomplete>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof autocomplete>>,
          TError,
          Awaited<ReturnType<typeof autocomplete>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAutocomplete<TData = Awaited<ReturnType<typeof autocomplete>>, TError = unknown>(
 params: AutocompleteParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof autocomplete>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useAutocomplete<TData = Awaited<ReturnType<typeof autocomplete>>, TError = unknown>(
 params: AutocompleteParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof autocomplete>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAutocompleteQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




