/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';


type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;




/**
 * 해당 영상에 최고예요를 표시합니다.
 * @summary 슈퍼라이크(왕따봉) 누르기
 */
export type superLikeVideoResponse200 = {
  data: Blob
  status: 200
}

export type superLikeVideoResponseSuccess = (superLikeVideoResponse200) & {
  headers: Headers;
};
;

export type superLikeVideoResponse = (superLikeVideoResponseSuccess)

export const getSuperLikeVideoUrl = (videoId: number,) => {


  

  return `/api/v1/interactions/${videoId}/superlike`
}

export const superLikeVideo = async (videoId: number, options?: RequestInit): Promise<superLikeVideoResponse> => {
  
  const res = await fetch(getSuperLikeVideoUrl(videoId),
  {      
    ...options,
    method: 'POST'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: superLikeVideoResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as superLikeVideoResponse
}
  



export const getSuperLikeVideoMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof superLikeVideo>>, TError,{videoId: number}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof superLikeVideo>>, TError,{videoId: number}, TContext> => {

const mutationKey = ['superLikeVideo'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof superLikeVideo>>, {videoId: number}> = (props) => {
          const {videoId} = props ?? {};

          return  superLikeVideo(videoId,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type SuperLikeVideoMutationResult = NonNullable<Awaited<ReturnType<typeof superLikeVideo>>>
    
    export type SuperLikeVideoMutationError = unknown

    /**
 * @summary 슈퍼라이크(왕따봉) 누르기
 */
export const useSuperLikeVideo = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof superLikeVideo>>, TError,{videoId: number}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof superLikeVideo>>,
        TError,
        {videoId: number},
        TContext
      > => {
      return useMutation(getSuperLikeVideoMutationOptions(options), queryClient);
    }
    /**
 * 해당 영상에 좋아요를 표시합니다.
 * @summary 좋아요 누르기
 */
export type likeVideoResponse200 = {
  data: Blob
  status: 200
}

export type likeVideoResponseSuccess = (likeVideoResponse200) & {
  headers: Headers;
};
;

export type likeVideoResponse = (likeVideoResponseSuccess)

export const getLikeVideoUrl = (videoId: number,) => {


  

  return `/api/v1/interactions/${videoId}/like`
}

export const likeVideo = async (videoId: number, options?: RequestInit): Promise<likeVideoResponse> => {
  
  const res = await fetch(getLikeVideoUrl(videoId),
  {      
    ...options,
    method: 'POST'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: likeVideoResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as likeVideoResponse
}
  



export const getLikeVideoMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof likeVideo>>, TError,{videoId: number}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof likeVideo>>, TError,{videoId: number}, TContext> => {

const mutationKey = ['likeVideo'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof likeVideo>>, {videoId: number}> = (props) => {
          const {videoId} = props ?? {};

          return  likeVideo(videoId,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type LikeVideoMutationResult = NonNullable<Awaited<ReturnType<typeof likeVideo>>>
    
    export type LikeVideoMutationError = unknown

    /**
 * @summary 좋아요 누르기
 */
export const useLikeVideo = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof likeVideo>>, TError,{videoId: number}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof likeVideo>>,
        TError,
        {videoId: number},
        TContext
      > => {
      return useMutation(getLikeVideoMutationOptions(options), queryClient);
    }
    /**
 * 해당 영상에 싫어요를 표시합니다.
 * @summary 싫어요 누르기
 */
export type dislikeVideoResponse200 = {
  data: Blob
  status: 200
}

export type dislikeVideoResponseSuccess = (dislikeVideoResponse200) & {
  headers: Headers;
};
;

export type dislikeVideoResponse = (dislikeVideoResponseSuccess)

export const getDislikeVideoUrl = (videoId: number,) => {


  

  return `/api/v1/interactions/${videoId}/dislike`
}

export const dislikeVideo = async (videoId: number, options?: RequestInit): Promise<dislikeVideoResponse> => {
  
  const res = await fetch(getDislikeVideoUrl(videoId),
  {      
    ...options,
    method: 'POST'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: dislikeVideoResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as dislikeVideoResponse
}
  



export const getDislikeVideoMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof dislikeVideo>>, TError,{videoId: number}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof dislikeVideo>>, TError,{videoId: number}, TContext> => {

const mutationKey = ['dislikeVideo'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof dislikeVideo>>, {videoId: number}> = (props) => {
          const {videoId} = props ?? {};

          return  dislikeVideo(videoId,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DislikeVideoMutationResult = NonNullable<Awaited<ReturnType<typeof dislikeVideo>>>
    
    export type DislikeVideoMutationError = unknown

    /**
 * @summary 싫어요 누르기
 */
export const useDislikeVideo = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof dislikeVideo>>, TError,{videoId: number}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof dislikeVideo>>,
        TError,
        {videoId: number},
        TContext
      > => {
      return useMutation(getDislikeVideoMutationOptions(options), queryClient);
    }
    /**
 * 내가 이 영상에 좋아요/싫어요를 했는지 확인합니다.
 * @summary 내 반응 조회
 */
export type getMyInteractionStatusResponse200 = {
  data: Blob
  status: 200
}

export type getMyInteractionStatusResponseSuccess = (getMyInteractionStatusResponse200) & {
  headers: Headers;
};
;

export type getMyInteractionStatusResponse = (getMyInteractionStatusResponseSuccess)

export const getGetMyInteractionStatusUrl = (videoId: number,) => {


  

  return `/api/v1/interactions/${videoId}/my-status`
}

export const getMyInteractionStatus = async (videoId: number, options?: RequestInit): Promise<getMyInteractionStatusResponse> => {
  
  const res = await fetch(getGetMyInteractionStatusUrl(videoId),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getMyInteractionStatusResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getMyInteractionStatusResponse
}
  




export const getGetMyInteractionStatusQueryKey = (videoId: number,) => {
    return [
    `/api/v1/interactions/${videoId}/my-status`
    ] as const;
    }

    
export const getGetMyInteractionStatusQueryOptions = <TData = Awaited<ReturnType<typeof getMyInteractionStatus>>, TError = unknown>(videoId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyInteractionStatus>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMyInteractionStatusQueryKey(videoId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMyInteractionStatus>>> = ({ signal }) => getMyInteractionStatus(videoId, { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(videoId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMyInteractionStatus>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMyInteractionStatusQueryResult = NonNullable<Awaited<ReturnType<typeof getMyInteractionStatus>>>
export type GetMyInteractionStatusQueryError = unknown


export function useGetMyInteractionStatus<TData = Awaited<ReturnType<typeof getMyInteractionStatus>>, TError = unknown>(
 videoId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyInteractionStatus>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyInteractionStatus>>,
          TError,
          Awaited<ReturnType<typeof getMyInteractionStatus>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMyInteractionStatus<TData = Awaited<ReturnType<typeof getMyInteractionStatus>>, TError = unknown>(
 videoId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyInteractionStatus>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyInteractionStatus>>,
          TError,
          Awaited<ReturnType<typeof getMyInteractionStatus>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMyInteractionStatus<TData = Awaited<ReturnType<typeof getMyInteractionStatus>>, TError = unknown>(
 videoId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyInteractionStatus>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 내 반응 조회
 */

export function useGetMyInteractionStatus<TData = Awaited<ReturnType<typeof getMyInteractionStatus>>, TError = unknown>(
 videoId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyInteractionStatus>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMyInteractionStatusQueryOptions(videoId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




