/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetBookmarkListParams
} from '.././model';


type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;




/**
 * 누를 때마다 찜 상태가 켜지거나 꺼집니다.
 * @summary 찜하기(북마크) 토글
 */
export type toggleBookmarkResponse200 = {
  data: Blob
  status: 200
}

export type toggleBookmarkResponseSuccess = (toggleBookmarkResponse200) & {
  headers: Headers;
};
;

export type toggleBookmarkResponse = (toggleBookmarkResponseSuccess)

export const getToggleBookmarkUrl = (videoId: number,) => {


  

  return `/api/v1/bookmarks/${videoId}`
}

export const toggleBookmark = async (videoId: number, options?: RequestInit): Promise<toggleBookmarkResponse> => {
  
  const res = await fetch(getToggleBookmarkUrl(videoId),
  {      
    ...options,
    method: 'POST'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: toggleBookmarkResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as toggleBookmarkResponse
}
  



export const getToggleBookmarkMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof toggleBookmark>>, TError,{videoId: number}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof toggleBookmark>>, TError,{videoId: number}, TContext> => {

const mutationKey = ['toggleBookmark'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof toggleBookmark>>, {videoId: number}> = (props) => {
          const {videoId} = props ?? {};

          return  toggleBookmark(videoId,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type ToggleBookmarkMutationResult = NonNullable<Awaited<ReturnType<typeof toggleBookmark>>>
    
    export type ToggleBookmarkMutationError = unknown

    /**
 * @summary 찜하기(북마크) 토글
 */
export const useToggleBookmark = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof toggleBookmark>>, TError,{videoId: number}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof toggleBookmark>>,
        TError,
        {videoId: number},
        TContext
      > => {
      return useMutation(getToggleBookmarkMutationOptions(options), queryClient);
    }
    /**
 * 찜한 영상을 videoType으로 필터링하여 페이지네이션으로 조회합니다.
 * @summary 찜한 영상 목록 조회
 */
export type getBookmarkListResponse200 = {
  data: Blob
  status: 200
}

export type getBookmarkListResponseSuccess = (getBookmarkListResponse200) & {
  headers: Headers;
};
;

export type getBookmarkListResponse = (getBookmarkListResponseSuccess)

export const getGetBookmarkListUrl = (params: GetBookmarkListParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/bookmarks?${stringifiedParams}` : `/api/v1/bookmarks`
}

export const getBookmarkList = async (params: GetBookmarkListParams, options?: RequestInit): Promise<getBookmarkListResponse> => {
  
  const res = await fetch(getGetBookmarkListUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getBookmarkListResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getBookmarkListResponse
}
  




export const getGetBookmarkListQueryKey = (params?: GetBookmarkListParams,) => {
    return [
    `/api/v1/bookmarks`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetBookmarkListQueryOptions = <TData = Awaited<ReturnType<typeof getBookmarkList>>, TError = unknown>(params: GetBookmarkListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBookmarkList>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetBookmarkListQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getBookmarkList>>> = ({ signal }) => getBookmarkList(params, { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getBookmarkList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetBookmarkListQueryResult = NonNullable<Awaited<ReturnType<typeof getBookmarkList>>>
export type GetBookmarkListQueryError = unknown


export function useGetBookmarkList<TData = Awaited<ReturnType<typeof getBookmarkList>>, TError = unknown>(
 params: GetBookmarkListParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBookmarkList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBookmarkList>>,
          TError,
          Awaited<ReturnType<typeof getBookmarkList>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetBookmarkList<TData = Awaited<ReturnType<typeof getBookmarkList>>, TError = unknown>(
 params: GetBookmarkListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBookmarkList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBookmarkList>>,
          TError,
          Awaited<ReturnType<typeof getBookmarkList>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetBookmarkList<TData = Awaited<ReturnType<typeof getBookmarkList>>, TError = unknown>(
 params: GetBookmarkListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBookmarkList>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 찜한 영상 목록 조회
 */

export function useGetBookmarkList<TData = Awaited<ReturnType<typeof getBookmarkList>>, TError = unknown>(
 params: GetBookmarkListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBookmarkList>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetBookmarkListQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * 내가 이 영상을 찜했는지 확인합니다.
 * @summary 북마크 여부 조회
 */
export type getBookmarkStatusResponse200 = {
  data: Blob
  status: 200
}

export type getBookmarkStatusResponseSuccess = (getBookmarkStatusResponse200) & {
  headers: Headers;
};
;

export type getBookmarkStatusResponse = (getBookmarkStatusResponseSuccess)

export const getGetBookmarkStatusUrl = (videoId: number,) => {


  

  return `/api/v1/bookmarks/${videoId}/status`
}

export const getBookmarkStatus = async (videoId: number, options?: RequestInit): Promise<getBookmarkStatusResponse> => {
  
  const res = await fetch(getGetBookmarkStatusUrl(videoId),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getBookmarkStatusResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getBookmarkStatusResponse
}
  




export const getGetBookmarkStatusQueryKey = (videoId: number,) => {
    return [
    `/api/v1/bookmarks/${videoId}/status`
    ] as const;
    }

    
export const getGetBookmarkStatusQueryOptions = <TData = Awaited<ReturnType<typeof getBookmarkStatus>>, TError = unknown>(videoId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBookmarkStatus>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetBookmarkStatusQueryKey(videoId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getBookmarkStatus>>> = ({ signal }) => getBookmarkStatus(videoId, { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(videoId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getBookmarkStatus>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetBookmarkStatusQueryResult = NonNullable<Awaited<ReturnType<typeof getBookmarkStatus>>>
export type GetBookmarkStatusQueryError = unknown


export function useGetBookmarkStatus<TData = Awaited<ReturnType<typeof getBookmarkStatus>>, TError = unknown>(
 videoId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBookmarkStatus>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBookmarkStatus>>,
          TError,
          Awaited<ReturnType<typeof getBookmarkStatus>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetBookmarkStatus<TData = Awaited<ReturnType<typeof getBookmarkStatus>>, TError = unknown>(
 videoId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBookmarkStatus>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBookmarkStatus>>,
          TError,
          Awaited<ReturnType<typeof getBookmarkStatus>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetBookmarkStatus<TData = Awaited<ReturnType<typeof getBookmarkStatus>>, TError = unknown>(
 videoId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBookmarkStatus>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 북마크 여부 조회
 */

export function useGetBookmarkStatus<TData = Awaited<ReturnType<typeof getBookmarkStatus>>, TError = unknown>(
 videoId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBookmarkStatus>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetBookmarkStatusQueryOptions(videoId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * 찜한 영상의 타입별 개수 요약 정보를 반환합니다.
 * @summary 찜 재생목록 요약 조회
 */
export type getBookmarkSummaryResponse200 = {
  data: Blob
  status: 200
}

export type getBookmarkSummaryResponseSuccess = (getBookmarkSummaryResponse200) & {
  headers: Headers;
};
;

export type getBookmarkSummaryResponse = (getBookmarkSummaryResponseSuccess)

export const getGetBookmarkSummaryUrl = () => {


  

  return `/api/v1/bookmarks/summary`
}

export const getBookmarkSummary = async ( options?: RequestInit): Promise<getBookmarkSummaryResponse> => {
  
  const res = await fetch(getGetBookmarkSummaryUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getBookmarkSummaryResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getBookmarkSummaryResponse
}
  




export const getGetBookmarkSummaryQueryKey = () => {
    return [
    `/api/v1/bookmarks/summary`
    ] as const;
    }

    
export const getGetBookmarkSummaryQueryOptions = <TData = Awaited<ReturnType<typeof getBookmarkSummary>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBookmarkSummary>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetBookmarkSummaryQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getBookmarkSummary>>> = ({ signal }) => getBookmarkSummary({ signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getBookmarkSummary>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetBookmarkSummaryQueryResult = NonNullable<Awaited<ReturnType<typeof getBookmarkSummary>>>
export type GetBookmarkSummaryQueryError = unknown


export function useGetBookmarkSummary<TData = Awaited<ReturnType<typeof getBookmarkSummary>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBookmarkSummary>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBookmarkSummary>>,
          TError,
          Awaited<ReturnType<typeof getBookmarkSummary>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetBookmarkSummary<TData = Awaited<ReturnType<typeof getBookmarkSummary>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBookmarkSummary>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBookmarkSummary>>,
          TError,
          Awaited<ReturnType<typeof getBookmarkSummary>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetBookmarkSummary<TData = Awaited<ReturnType<typeof getBookmarkSummary>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBookmarkSummary>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 찜 재생목록 요약 조회
 */

export function useGetBookmarkSummary<TData = Awaited<ReturnType<typeof getBookmarkSummary>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBookmarkSummary>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetBookmarkSummaryQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




