/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type { DeleteUserParams, UpdateUserRequest } from ".././model";

import { customMutator } from "../../lib/mutator";

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * 본인이 계정을 일시적으로 비활성화합니다.
 * @summary 사용자 비활성화
 */
export type deactivateUserResponse200 = {
  data: Blob;
  status: 200;
};

export type deactivateUserResponseSuccess = deactivateUserResponse200 & {
  headers: Headers;
};
export type deactivateUserResponse = deactivateUserResponseSuccess;

export const getDeactivateUserUrl = (userId: number) => {
  return `/api/v1/users/${userId}/deactivate`;
};

export const deactivateUser = async (
  userId: number,
  options?: RequestInit,
): Promise<deactivateUserResponse> => {
  return customMutator<deactivateUserResponse>(getDeactivateUserUrl(userId), {
    ...options,
    method: "POST",
  });
};

export const getDeactivateUserMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deactivateUser>>,
    TError,
    { userId: number },
    TContext
  >;
  request?: SecondParameter<typeof customMutator>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deactivateUser>>,
  TError,
  { userId: number },
  TContext
> => {
  const mutationKey = ["deactivateUser"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deactivateUser>>,
    { userId: number }
  > = (props) => {
    const { userId } = props ?? {};

    return deactivateUser(userId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeactivateUserMutationResult = NonNullable<
  Awaited<ReturnType<typeof deactivateUser>>
>;

export type DeactivateUserMutationError = unknown;

/**
 * @summary 사용자 비활성화
 */
export const useDeactivateUser = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deactivateUser>>,
      TError,
      { userId: number },
      TContext
    >;
    request?: SecondParameter<typeof customMutator>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deactivateUser>>,
  TError,
  { userId: number },
  TContext
> => {
  return useMutation(getDeactivateUserMutationOptions(options), queryClient);
};
/**
 * 본인 또는 관리자가 사용자 상세 정보를 조회합니다.
 * @summary 사용자 상세 조회
 */
export type getUserDetailResponse200 = {
  data: Blob;
  status: 200;
};

export type getUserDetailResponseSuccess = getUserDetailResponse200 & {
  headers: Headers;
};
export type getUserDetailResponse = getUserDetailResponseSuccess;

export const getGetUserDetailUrl = (userId: number) => {
  return `/api/v1/users/${userId}`;
};

export const getUserDetail = async (
  userId: number,
  options?: RequestInit,
): Promise<getUserDetailResponse> => {
  return customMutator<getUserDetailResponse>(getGetUserDetailUrl(userId), {
    ...options,
    method: "GET",
  });
};

export const getGetUserDetailQueryKey = (userId: number) => {
  return [`/api/v1/users/${userId}`] as const;
};

export const getGetUserDetailQueryOptions = <
  TData = Awaited<ReturnType<typeof getUserDetail>>,
  TError = unknown,
>(
  userId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUserDetail>>, TError, TData>
    >;
    request?: SecondParameter<typeof customMutator>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetUserDetailQueryKey(userId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserDetail>>> = ({
    signal,
  }) => getUserDetail(userId, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!userId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getUserDetail>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetUserDetailQueryResult = NonNullable<
  Awaited<ReturnType<typeof getUserDetail>>
>;
export type GetUserDetailQueryError = unknown;

export function useGetUserDetail<
  TData = Awaited<ReturnType<typeof getUserDetail>>,
  TError = unknown,
>(
  userId: number,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUserDetail>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserDetail>>,
          TError,
          Awaited<ReturnType<typeof getUserDetail>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customMutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetUserDetail<
  TData = Awaited<ReturnType<typeof getUserDetail>>,
  TError = unknown,
>(
  userId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUserDetail>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserDetail>>,
          TError,
          Awaited<ReturnType<typeof getUserDetail>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetUserDetail<
  TData = Awaited<ReturnType<typeof getUserDetail>>,
  TError = unknown,
>(
  userId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUserDetail>>, TError, TData>
    >;
    request?: SecondParameter<typeof customMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 사용자 상세 조회
 */

export function useGetUserDetail<
  TData = Awaited<ReturnType<typeof getUserDetail>>,
  TError = unknown,
>(
  userId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUserDetail>>, TError, TData>
    >;
    request?: SecondParameter<typeof customMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetUserDetailQueryOptions(userId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * 본인 또는 관리자가 사용자를 삭제(soft delete)합니다.
 * @summary 사용자 탈퇴
 */
export type deleteUserResponse200 = {
  data: Blob;
  status: 200;
};

export type deleteUserResponseSuccess = deleteUserResponse200 & {
  headers: Headers;
};
export type deleteUserResponse = deleteUserResponseSuccess;

export const getDeleteUserUrl = (userId: number, params: DeleteUserParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/users/${userId}?${stringifiedParams}`
    : `/api/v1/users/${userId}`;
};

export const deleteUser = async (
  userId: number,
  params: DeleteUserParams,
  options?: RequestInit,
): Promise<deleteUserResponse> => {
  return customMutator<deleteUserResponse>(getDeleteUserUrl(userId, params), {
    ...options,
    method: "DELETE",
  });
};

export const getDeleteUserMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteUser>>,
    TError,
    { userId: number; params: DeleteUserParams },
    TContext
  >;
  request?: SecondParameter<typeof customMutator>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteUser>>,
  TError,
  { userId: number; params: DeleteUserParams },
  TContext
> => {
  const mutationKey = ["deleteUser"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteUser>>,
    { userId: number; params: DeleteUserParams }
  > = (props) => {
    const { userId, params } = props ?? {};

    return deleteUser(userId, params, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteUserMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteUser>>
>;

export type DeleteUserMutationError = unknown;

/**
 * @summary 사용자 탈퇴
 */
export const useDeleteUser = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteUser>>,
      TError,
      { userId: number; params: DeleteUserParams },
      TContext
    >;
    request?: SecondParameter<typeof customMutator>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteUser>>,
  TError,
  { userId: number; params: DeleteUserParams },
  TContext
> => {
  return useMutation(getDeleteUserMutationOptions(options), queryClient);
};
/**
 * 본인만 닉네임, 비밀번호, 프로필 이미지, 관심 태그를 수정할 수 있습니다.
 * @summary 사용자 정보 수정
 */
export type updateUserResponse200 = {
  data: Blob;
  status: 200;
};

export type updateUserResponseSuccess = updateUserResponse200 & {
  headers: Headers;
};
export type updateUserResponse = updateUserResponseSuccess;

export const getUpdateUserUrl = (userId: number) => {
  return `/api/v1/users/${userId}`;
};

export const updateUser = async (
  userId: number,
  updateUserRequest: UpdateUserRequest,
  options?: RequestInit,
): Promise<updateUserResponse> => {
  return customMutator<updateUserResponse>(getUpdateUserUrl(userId), {
    ...options,
    method: "PATCH",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(updateUserRequest),
  });
};

export const getUpdateUserMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateUser>>,
    TError,
    { userId: number; data: UpdateUserRequest },
    TContext
  >;
  request?: SecondParameter<typeof customMutator>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateUser>>,
  TError,
  { userId: number; data: UpdateUserRequest },
  TContext
> => {
  const mutationKey = ["updateUser"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateUser>>,
    { userId: number; data: UpdateUserRequest }
  > = (props) => {
    const { userId, data } = props ?? {};

    return updateUser(userId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateUserMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateUser>>
>;
export type UpdateUserMutationBody = UpdateUserRequest;
export type UpdateUserMutationError = unknown;

/**
 * @summary 사용자 정보 수정
 */
export const useUpdateUser = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateUser>>,
      TError,
      { userId: number; data: UpdateUserRequest },
      TContext
    >;
    request?: SecondParameter<typeof customMutator>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateUser>>,
  TError,
  { userId: number; data: UpdateUserRequest },
  TContext
> => {
  return useMutation(getUpdateUserMutationOptions(options), queryClient);
};
