/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';


type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;




/**
 * PostgreSQL에 저장된 모든 비디오 및 태그 메타데이터를 엘라스틱서치로 벌크 인덱싱(Bulk Indexing)합니다.<br>
- <b>안전장치:</b> 1,000건 단위 분할 처리(Paging) 및 N+1 쿼리 최적화 적용됨.

 * @summary DB ➔ 엘라스틱서치 전체 데이터 동기화
 */
export type syncDataResponse200 = {
  data: Blob
  status: 200
}

export type syncDataResponseSuccess = (syncDataResponse200) & {
  headers: Headers;
};
;

export type syncDataResponse = (syncDataResponseSuccess)

export const getSyncDataUrl = () => {


  

  return `/api/v1/search/admin/sync`
}

export const syncData = async ( options?: RequestInit): Promise<syncDataResponse> => {
  
  const res = await fetch(getSyncDataUrl(),
  {      
    ...options,
    method: 'POST'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: syncDataResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as syncDataResponse
}
  



export const getSyncDataMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof syncData>>, TError,void, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof syncData>>, TError,void, TContext> => {

const mutationKey = ['syncData'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof syncData>>, void> = () => {
          

          return  syncData(fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type SyncDataMutationResult = NonNullable<Awaited<ReturnType<typeof syncData>>>
    
    export type SyncDataMutationError = unknown

    /**
 * @summary DB ➔ 엘라스틱서치 전체 데이터 동기화
 */
export const useSyncData = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof syncData>>, TError,void, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof syncData>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getSyncDataMutationOptions(options), queryClient);
    }
    