/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type { RegisterRequest } from ".././model";

import { customMutator } from "../../lib/mutator";

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * 현재 로그인한 사용자의 U+ 가입 정보를 반환합니다.
 * @summary 내 U+ 가입 정보 조회
 */
export type getMySubscriptionResponse200 = {
  data: Blob;
  status: 200;
};

export type getMySubscriptionResponseSuccess = getMySubscriptionResponse200 & {
  headers: Headers;
};
export type getMySubscriptionResponse = getMySubscriptionResponseSuccess;

export const getGetMySubscriptionUrl = () => {
  return `/api/v1/uplus/subscription`;
};

export const getMySubscription = async (
  options?: RequestInit,
): Promise<getMySubscriptionResponse> => {
  return customMutator<getMySubscriptionResponse>(getGetMySubscriptionUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetMySubscriptionQueryKey = () => {
  return [`/api/v1/uplus/subscription`] as const;
};

export const getGetMySubscriptionQueryOptions = <
  TData = Awaited<ReturnType<typeof getMySubscription>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getMySubscription>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customMutator>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetMySubscriptionQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getMySubscription>>
  > = ({ signal }) => getMySubscription({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getMySubscription>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetMySubscriptionQueryResult = NonNullable<
  Awaited<ReturnType<typeof getMySubscription>>
>;
export type GetMySubscriptionQueryError = unknown;

export function useGetMySubscription<
  TData = Awaited<ReturnType<typeof getMySubscription>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMySubscription>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMySubscription>>,
          TError,
          Awaited<ReturnType<typeof getMySubscription>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customMutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMySubscription<
  TData = Awaited<ReturnType<typeof getMySubscription>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMySubscription>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMySubscription>>,
          TError,
          Awaited<ReturnType<typeof getMySubscription>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMySubscription<
  TData = Awaited<ReturnType<typeof getMySubscription>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMySubscription>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 내 U+ 가입 정보 조회
 */

export function useGetMySubscription<
  TData = Awaited<ReturnType<typeof getMySubscription>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMySubscription>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetMySubscriptionQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * 전화번호 입력 시 U+ API에서 가입 여부와 요금제를 자동 조회하여 등록합니다.
 * @summary U+ 가입 정보 등록
 */
export type registerResponse200 = {
  data: Blob;
  status: 200;
};

export type registerResponseSuccess = registerResponse200 & {
  headers: Headers;
};
export type registerResponse = registerResponseSuccess;

export const getRegisterUrl = () => {
  return `/api/v1/uplus/subscription`;
};

export const register = async (
  registerRequest: RegisterRequest,
  options?: RequestInit,
): Promise<registerResponse> => {
  return customMutator<registerResponse>(getRegisterUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(registerRequest),
  });
};

export const getRegisterMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof register>>,
    TError,
    { data: RegisterRequest },
    TContext
  >;
  request?: SecondParameter<typeof customMutator>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof register>>,
  TError,
  { data: RegisterRequest },
  TContext
> => {
  const mutationKey = ["register"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof register>>,
    { data: RegisterRequest }
  > = (props) => {
    const { data } = props ?? {};

    return register(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RegisterMutationResult = NonNullable<
  Awaited<ReturnType<typeof register>>
>;
export type RegisterMutationBody = RegisterRequest;
export type RegisterMutationError = unknown;

/**
 * @summary U+ 가입 정보 등록
 */
export const useRegister = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof register>>,
      TError,
      { data: RegisterRequest },
      TContext
    >;
    request?: SecondParameter<typeof customMutator>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof register>>,
  TError,
  { data: RegisterRequest },
  TContext
> => {
  return useMutation(getRegisterMutationOptions(options), queryClient);
};
/**
 * U+ 가입 정보를 해지(soft delete) 처리합니다.
 * @summary U+ 구독 해지
 */
export type deactivateResponse200 = {
  data: Blob;
  status: 200;
};

export type deactivateResponseSuccess = deactivateResponse200 & {
  headers: Headers;
};
export type deactivateResponse = deactivateResponseSuccess;

export const getDeactivateUrl = () => {
  return `/api/v1/uplus/subscription`;
};

export const deactivate = async (
  options?: RequestInit,
): Promise<deactivateResponse> => {
  return customMutator<deactivateResponse>(getDeactivateUrl(), {
    ...options,
    method: "DELETE",
  });
};

export const getDeactivateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deactivate>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customMutator>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deactivate>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["deactivate"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deactivate>>,
    void
  > = () => {
    return deactivate(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeactivateMutationResult = NonNullable<
  Awaited<ReturnType<typeof deactivate>>
>;

export type DeactivateMutationError = unknown;

/**
 * @summary U+ 구독 해지
 */
export const useDeactivate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deactivate>>,
      TError,
      void,
      TContext
    >;
    request?: SecondParameter<typeof customMutator>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deactivate>>,
  TError,
  void,
  TContext
> => {
  return useMutation(getDeactivateMutationOptions(options), queryClient);
};
/**
 * U+ API를 재조회하여 최신 요금제로 업데이트합니다.
 * @summary 요금제 동기화
 */
export type syncPlanResponse200 = {
  data: Blob;
  status: 200;
};

export type syncPlanResponseSuccess = syncPlanResponse200 & {
  headers: Headers;
};
export type syncPlanResponse = syncPlanResponseSuccess;

export const getSyncPlanUrl = () => {
  return `/api/v1/uplus/subscription/plan`;
};

export const syncPlan = async (
  options?: RequestInit,
): Promise<syncPlanResponse> => {
  return customMutator<syncPlanResponse>(getSyncPlanUrl(), {
    ...options,
    method: "PATCH",
  });
};

export const getSyncPlanMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof syncPlan>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customMutator>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof syncPlan>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["syncPlan"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof syncPlan>>,
    void
  > = () => {
    return syncPlan(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type SyncPlanMutationResult = NonNullable<
  Awaited<ReturnType<typeof syncPlan>>
>;

export type SyncPlanMutationError = unknown;

/**
 * @summary 요금제 동기화
 */
export const useSyncPlan = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof syncPlan>>,
      TError,
      void,
      TContext
    >;
    request?: SecondParameter<typeof customMutator>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof syncPlan>>,
  TError,
  void,
  TContext
> => {
  return useMutation(getSyncPlanMutationOptions(options), queryClient);
};
/**
 * 비로그인 사용자도 조회 가능한 U+ 요금제 목록을 반환합니다.
 * @summary 요금제 목록 조회
 */
export type getPlansResponse200 = {
  data: Blob;
  status: 200;
};

export type getPlansResponseSuccess = getPlansResponse200 & {
  headers: Headers;
};
export type getPlansResponse = getPlansResponseSuccess;

export const getGetPlansUrl = () => {
  return `/api/v1/uplus/plans`;
};

export const getPlans = async (
  options?: RequestInit,
): Promise<getPlansResponse> => {
  return customMutator<getPlansResponse>(getGetPlansUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetPlansQueryKey = () => {
  return [`/api/v1/uplus/plans`] as const;
};

export const getGetPlansQueryOptions = <
  TData = Awaited<ReturnType<typeof getPlans>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getPlans>>, TError, TData>
  >;
  request?: SecondParameter<typeof customMutator>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetPlansQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getPlans>>> = ({
    signal,
  }) => getPlans({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getPlans>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetPlansQueryResult = NonNullable<
  Awaited<ReturnType<typeof getPlans>>
>;
export type GetPlansQueryError = unknown;

export function useGetPlans<
  TData = Awaited<ReturnType<typeof getPlans>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getPlans>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPlans>>,
          TError,
          Awaited<ReturnType<typeof getPlans>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customMutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetPlans<
  TData = Awaited<ReturnType<typeof getPlans>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getPlans>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPlans>>,
          TError,
          Awaited<ReturnType<typeof getPlans>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetPlans<
  TData = Awaited<ReturnType<typeof getPlans>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getPlans>>, TError, TData>
    >;
    request?: SecondParameter<typeof customMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 요금제 목록 조회
 */

export function useGetPlans<
  TData = Awaited<ReturnType<typeof getPlans>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getPlans>>, TError, TData>
    >;
    request?: SecondParameter<typeof customMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetPlansQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * 현재 로그인한 사용자의 U+ 포인트 할인 이력을 최근 순으로 반환합니다.
 * @summary 포인트 할인 이력 조회
 */
export type getDiscountHistoryResponse200 = {
  data: Blob;
  status: 200;
};

export type getDiscountHistoryResponseSuccess =
  getDiscountHistoryResponse200 & {
    headers: Headers;
  };
export type getDiscountHistoryResponse = getDiscountHistoryResponseSuccess;

export const getGetDiscountHistoryUrl = () => {
  return `/api/v1/uplus/discount/history`;
};

export const getDiscountHistory = async (
  options?: RequestInit,
): Promise<getDiscountHistoryResponse> => {
  return customMutator<getDiscountHistoryResponse>(getGetDiscountHistoryUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetDiscountHistoryQueryKey = () => {
  return [`/api/v1/uplus/discount/history`] as const;
};

export const getGetDiscountHistoryQueryOptions = <
  TData = Awaited<ReturnType<typeof getDiscountHistory>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getDiscountHistory>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customMutator>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetDiscountHistoryQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getDiscountHistory>>
  > = ({ signal }) => getDiscountHistory({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getDiscountHistory>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetDiscountHistoryQueryResult = NonNullable<
  Awaited<ReturnType<typeof getDiscountHistory>>
>;
export type GetDiscountHistoryQueryError = unknown;

export function useGetDiscountHistory<
  TData = Awaited<ReturnType<typeof getDiscountHistory>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getDiscountHistory>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDiscountHistory>>,
          TError,
          Awaited<ReturnType<typeof getDiscountHistory>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customMutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetDiscountHistory<
  TData = Awaited<ReturnType<typeof getDiscountHistory>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getDiscountHistory>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDiscountHistory>>,
          TError,
          Awaited<ReturnType<typeof getDiscountHistory>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetDiscountHistory<
  TData = Awaited<ReturnType<typeof getDiscountHistory>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getDiscountHistory>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 포인트 할인 이력 조회
 */

export function useGetDiscountHistory<
  TData = Awaited<ReturnType<typeof getDiscountHistory>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getDiscountHistory>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetDiscountHistoryQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
