/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AbortMultipartUploadParams,
  MultipartCompleteRequest,
  MultipartInitRequest,
  VideoUploadMultipart
} from '.././model';


type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;




/**
 * multipart/form-data로 image(파일)과 data(JSON)를 함께 전송합니다.
 * @summary 비디오 업로드 (썸네일 + 메타데이터)
 */
export type uploadResponse200 = {
  data: Blob
  status: 200
}

export type uploadResponseSuccess = (uploadResponse200) & {
  headers: Headers;
};
;

export type uploadResponse = (uploadResponseSuccess)

export const getUploadUrl = (videoId: number,) => {


  

  return `/api/v1/videos/${videoId}/upload`
}

export const upload = async (videoId: number,
    videoUploadMultipart: VideoUploadMultipart, options?: RequestInit): Promise<uploadResponse> => {
    const formData = new FormData();
if(videoUploadMultipart.image !== undefined) {
 formData.append(`image`, videoUploadMultipart.image);
 }
if(videoUploadMultipart.data !== undefined) {
 formData.append(`data`, new Blob([JSON.stringify(videoUploadMultipart.data)], { type: 'application/json' }));
 }

  const res = await fetch(getUploadUrl(videoId),
  {      
    ...options,
    method: 'POST'
    ,
    body: 
      formData,
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: uploadResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as uploadResponse
}
  



export const getUploadMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof upload>>, TError,{videoId: number;data: VideoUploadMultipart}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof upload>>, TError,{videoId: number;data: VideoUploadMultipart}, TContext> => {

const mutationKey = ['upload'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof upload>>, {videoId: number;data: VideoUploadMultipart}> = (props) => {
          const {videoId,data} = props ?? {};

          return  upload(videoId,data,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UploadMutationResult = NonNullable<Awaited<ReturnType<typeof upload>>>
    export type UploadMutationBody = VideoUploadMultipart
    export type UploadMutationError = unknown

    /**
 * @summary 비디오 업로드 (썸네일 + 메타데이터)
 */
export const useUpload = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof upload>>, TError,{videoId: number;data: VideoUploadMultipart}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof upload>>,
        TError,
        {videoId: number;data: VideoUploadMultipart},
        TContext
      > => {
      return useMutation(getUploadMutationOptions(options), queryClient);
    }
    /**
 * 클라이언트가 업로드한 parts 정보를 바탕으로 Multipart Upload를 Complete 합니다.
 * @summary Multipart 업로드 완료
 */
export type completeMultipartUploadResponse200 = {
  data: Blob
  status: 200
}

export type completeMultipartUploadResponseSuccess = (completeMultipartUploadResponse200) & {
  headers: Headers;
};
;

export type completeMultipartUploadResponse = (completeMultipartUploadResponseSuccess)

export const getCompleteMultipartUploadUrl = (videoId: number,) => {


  

  return `/api/v1/videos/${videoId}/upload/multipart/complete`
}

export const completeMultipartUpload = async (videoId: number,
    multipartCompleteRequest: MultipartCompleteRequest, options?: RequestInit): Promise<completeMultipartUploadResponse> => {
  
  const res = await fetch(getCompleteMultipartUploadUrl(videoId),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      multipartCompleteRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: completeMultipartUploadResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as completeMultipartUploadResponse
}
  



export const getCompleteMultipartUploadMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof completeMultipartUpload>>, TError,{videoId: number;data: MultipartCompleteRequest}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof completeMultipartUpload>>, TError,{videoId: number;data: MultipartCompleteRequest}, TContext> => {

const mutationKey = ['completeMultipartUpload'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof completeMultipartUpload>>, {videoId: number;data: MultipartCompleteRequest}> = (props) => {
          const {videoId,data} = props ?? {};

          return  completeMultipartUpload(videoId,data,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CompleteMultipartUploadMutationResult = NonNullable<Awaited<ReturnType<typeof completeMultipartUpload>>>
    export type CompleteMultipartUploadMutationBody = MultipartCompleteRequest
    export type CompleteMultipartUploadMutationError = unknown

    /**
 * @summary Multipart 업로드 완료
 */
export const useCompleteMultipartUpload = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof completeMultipartUpload>>, TError,{videoId: number;data: MultipartCompleteRequest}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof completeMultipartUpload>>,
        TError,
        {videoId: number;data: MultipartCompleteRequest},
        TContext
      > => {
      return useMutation(getCompleteMultipartUploadMutationOptions(options), queryClient);
    }
    /**
 * 업로드를 중단하고 MultipartUploadId 기준으로 abort 처리합니다.
 * @summary Multipart 업로드 중단(Abort)
 */
export type abortMultipartUploadResponse200 = {
  data: Blob
  status: 200
}

export type abortMultipartUploadResponseSuccess = (abortMultipartUploadResponse200) & {
  headers: Headers;
};
;

export type abortMultipartUploadResponse = (abortMultipartUploadResponseSuccess)

export const getAbortMultipartUploadUrl = (videoId: number,
    params: AbortMultipartUploadParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/videos/${videoId}/upload/multipart/abort?${stringifiedParams}` : `/api/v1/videos/${videoId}/upload/multipart/abort`
}

export const abortMultipartUpload = async (videoId: number,
    params: AbortMultipartUploadParams, options?: RequestInit): Promise<abortMultipartUploadResponse> => {
  
  const res = await fetch(getAbortMultipartUploadUrl(videoId,params),
  {      
    ...options,
    method: 'POST'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: abortMultipartUploadResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as abortMultipartUploadResponse
}
  



export const getAbortMultipartUploadMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof abortMultipartUpload>>, TError,{videoId: number;params: AbortMultipartUploadParams}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof abortMultipartUpload>>, TError,{videoId: number;params: AbortMultipartUploadParams}, TContext> => {

const mutationKey = ['abortMultipartUpload'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof abortMultipartUpload>>, {videoId: number;params: AbortMultipartUploadParams}> = (props) => {
          const {videoId,params} = props ?? {};

          return  abortMultipartUpload(videoId,params,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type AbortMultipartUploadMutationResult = NonNullable<Awaited<ReturnType<typeof abortMultipartUpload>>>
    
    export type AbortMultipartUploadMutationError = unknown

    /**
 * @summary Multipart 업로드 중단(Abort)
 */
export const useAbortMultipartUpload = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof abortMultipartUpload>>, TError,{videoId: number;params: AbortMultipartUploadParams}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof abortMultipartUpload>>,
        TError,
        {videoId: number;params: AbortMultipartUploadParams},
        TContext
      > => {
      return useMutation(getAbortMultipartUploadMutationOptions(options), queryClient);
    }
    /**
 * S3 Multipart Upload를 시작하고, uploadId/videoId/Presigned URL 발급 등 필요한 정보를 생성합니다.
 * @summary Multipart 업로드 초기화
 */
export type initMultipartUploadResponse200 = {
  data: Blob
  status: 200
}

export type initMultipartUploadResponseSuccess = (initMultipartUploadResponse200) & {
  headers: Headers;
};
;

export type initMultipartUploadResponse = (initMultipartUploadResponseSuccess)

export const getInitMultipartUploadUrl = () => {


  

  return `/api/v1/videos/upload/multipart/init`
}

export const initMultipartUpload = async (multipartInitRequest: MultipartInitRequest, options?: RequestInit): Promise<initMultipartUploadResponse> => {
  
  const res = await fetch(getInitMultipartUploadUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      multipartInitRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: initMultipartUploadResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as initMultipartUploadResponse
}
  



export const getInitMultipartUploadMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof initMultipartUpload>>, TError,{data: MultipartInitRequest}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof initMultipartUpload>>, TError,{data: MultipartInitRequest}, TContext> => {

const mutationKey = ['initMultipartUpload'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof initMultipartUpload>>, {data: MultipartInitRequest}> = (props) => {
          const {data} = props ?? {};

          return  initMultipartUpload(data,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type InitMultipartUploadMutationResult = NonNullable<Awaited<ReturnType<typeof initMultipartUpload>>>
    export type InitMultipartUploadMutationBody = MultipartInitRequest
    export type InitMultipartUploadMutationError = unknown

    /**
 * @summary Multipart 업로드 초기화
 */
export const useInitMultipartUpload = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof initMultipartUpload>>, TError,{data: MultipartInitRequest}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof initMultipartUpload>>,
        TError,
        {data: MultipartInitRequest},
        TContext
      > => {
      return useMutation(getInitMultipartUploadMutationOptions(options), queryClient);
    }
    /**
 * 영상 정보를 단일 조회합니다.
 * @summary 영상 단일 조회
 */
export type getVideoInfoResponse200 = {
  data: Blob
  status: 200
}

export type getVideoInfoResponseSuccess = (getVideoInfoResponse200) & {
  headers: Headers;
};
;

export type getVideoInfoResponse = (getVideoInfoResponseSuccess)

export const getGetVideoInfoUrl = (videoId: number,) => {


  

  return `/api/v1/videos/${videoId}`
}

export const getVideoInfo = async (videoId: number, options?: RequestInit): Promise<getVideoInfoResponse> => {
  
  const res = await fetch(getGetVideoInfoUrl(videoId),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getVideoInfoResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getVideoInfoResponse
}
  




export const getGetVideoInfoQueryKey = (videoId: number,) => {
    return [
    `/api/v1/videos/${videoId}`
    ] as const;
    }

    
export const getGetVideoInfoQueryOptions = <TData = Awaited<ReturnType<typeof getVideoInfo>>, TError = unknown>(videoId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVideoInfo>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetVideoInfoQueryKey(videoId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getVideoInfo>>> = ({ signal }) => getVideoInfo(videoId, { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(videoId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getVideoInfo>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetVideoInfoQueryResult = NonNullable<Awaited<ReturnType<typeof getVideoInfo>>>
export type GetVideoInfoQueryError = unknown


export function useGetVideoInfo<TData = Awaited<ReturnType<typeof getVideoInfo>>, TError = unknown>(
 videoId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVideoInfo>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVideoInfo>>,
          TError,
          Awaited<ReturnType<typeof getVideoInfo>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetVideoInfo<TData = Awaited<ReturnType<typeof getVideoInfo>>, TError = unknown>(
 videoId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVideoInfo>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVideoInfo>>,
          TError,
          Awaited<ReturnType<typeof getVideoInfo>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetVideoInfo<TData = Awaited<ReturnType<typeof getVideoInfo>>, TError = unknown>(
 videoId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVideoInfo>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 영상 단일 조회
 */

export function useGetVideoInfo<TData = Awaited<ReturnType<typeof getVideoInfo>>, TError = unknown>(
 videoId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVideoInfo>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetVideoInfoQueryOptions(videoId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * 재생에 필요한 정보(m3u8 URL)를 반환합니다. 응답 헤더에 쿠키를 함께 내려줍니다.
 * @summary 비디오 재생
 */
export type playResponse200 = {
  data: Blob
  status: 200
}

export type playResponseSuccess = (playResponse200) & {
  headers: Headers;
};
;

export type playResponse = (playResponseSuccess)

export const getPlayUrl = (videoId: number,) => {


  

  return `/api/v1/videos/${videoId}/play`
}

export const play = async (videoId: number, options?: RequestInit): Promise<playResponse> => {
  
  const res = await fetch(getPlayUrl(videoId),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: playResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as playResponse
}
  




export const getPlayQueryKey = (videoId: number,) => {
    return [
    `/api/v1/videos/${videoId}/play`
    ] as const;
    }

    
export const getPlayQueryOptions = <TData = Awaited<ReturnType<typeof play>>, TError = unknown>(videoId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof play>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPlayQueryKey(videoId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof play>>> = ({ signal }) => play(videoId, { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(videoId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof play>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PlayQueryResult = NonNullable<Awaited<ReturnType<typeof play>>>
export type PlayQueryError = unknown


export function usePlay<TData = Awaited<ReturnType<typeof play>>, TError = unknown>(
 videoId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof play>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof play>>,
          TError,
          Awaited<ReturnType<typeof play>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePlay<TData = Awaited<ReturnType<typeof play>>, TError = unknown>(
 videoId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof play>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof play>>,
          TError,
          Awaited<ReturnType<typeof play>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePlay<TData = Awaited<ReturnType<typeof play>>, TError = unknown>(
 videoId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof play>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 비디오 재생
 */

export function usePlay<TData = Awaited<ReturnType<typeof play>>, TError = unknown>(
 videoId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof play>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPlayQueryOptions(videoId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




