/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  GetMyPointTransactionHistoryParams,
  ProductPurchaseRequest,
} from ".././model";

import { customMutator } from "../../lib/mutator";

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * 상품을 구매한 사용자에게 거래 내역에 따른 보상 포인트를 즉시 적립합니다.
 * @summary 상품 구매 보상 포인트 적립 (보너스 지급)
 */
export type rewardPurchasePointResponse200 = {
  data: Blob;
  status: 200;
};

export type rewardPurchasePointResponseSuccess =
  rewardPurchasePointResponse200 & {
    headers: Headers;
  };
export type rewardPurchasePointResponse = rewardPurchasePointResponseSuccess;

export const getRewardPurchasePointUrl = () => {
  return `/api/v1/point/reward/purchase`;
};

export const rewardPurchasePoint = async (
  productPurchaseRequest: ProductPurchaseRequest,
  options?: RequestInit,
): Promise<rewardPurchasePointResponse> => {
  return customMutator<rewardPurchasePointResponse>(
    getRewardPurchasePointUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(productPurchaseRequest),
    },
  );
};

export const getRewardPurchasePointMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof rewardPurchasePoint>>,
    TError,
    { data: ProductPurchaseRequest },
    TContext
  >;
  request?: SecondParameter<typeof customMutator>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof rewardPurchasePoint>>,
  TError,
  { data: ProductPurchaseRequest },
  TContext
> => {
  const mutationKey = ["rewardPurchasePoint"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof rewardPurchasePoint>>,
    { data: ProductPurchaseRequest }
  > = (props) => {
    const { data } = props ?? {};

    return rewardPurchasePoint(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RewardPurchasePointMutationResult = NonNullable<
  Awaited<ReturnType<typeof rewardPurchasePoint>>
>;
export type RewardPurchasePointMutationBody = ProductPurchaseRequest;
export type RewardPurchasePointMutationError = unknown;

/**
 * @summary 상품 구매 보상 포인트 적립 (보너스 지급)
 */
export const useRewardPurchasePoint = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof rewardPurchasePoint>>,
      TError,
      { data: ProductPurchaseRequest },
      TContext
    >;
    request?: SecondParameter<typeof customMutator>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof rewardPurchasePoint>>,
  TError,
  { data: ProductPurchaseRequest },
  TContext
> => {
  return useMutation(
    getRewardPurchasePointMutationOptions(options),
    queryClient,
  );
};
/**
 * 현재 인증된 사용자의 가용 포인트 밸런스를 조회합니다.
 * @summary 사용자 포인트 잔액 조회
 */
export type getMyPointBalanceResponse200 = {
  data: Blob;
  status: 200;
};

export type getMyPointBalanceResponseSuccess = getMyPointBalanceResponse200 & {
  headers: Headers;
};
export type getMyPointBalanceResponse = getMyPointBalanceResponseSuccess;

export const getGetMyPointBalanceUrl = () => {
  return `/api/v1/point`;
};

export const getMyPointBalance = async (
  options?: RequestInit,
): Promise<getMyPointBalanceResponse> => {
  return customMutator<getMyPointBalanceResponse>(getGetMyPointBalanceUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetMyPointBalanceQueryKey = () => {
  return [`/api/v1/point`] as const;
};

export const getGetMyPointBalanceQueryOptions = <
  TData = Awaited<ReturnType<typeof getMyPointBalance>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getMyPointBalance>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customMutator>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetMyPointBalanceQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getMyPointBalance>>
  > = ({ signal }) => getMyPointBalance({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getMyPointBalance>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetMyPointBalanceQueryResult = NonNullable<
  Awaited<ReturnType<typeof getMyPointBalance>>
>;
export type GetMyPointBalanceQueryError = unknown;

export function useGetMyPointBalance<
  TData = Awaited<ReturnType<typeof getMyPointBalance>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMyPointBalance>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyPointBalance>>,
          TError,
          Awaited<ReturnType<typeof getMyPointBalance>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customMutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMyPointBalance<
  TData = Awaited<ReturnType<typeof getMyPointBalance>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMyPointBalance>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyPointBalance>>,
          TError,
          Awaited<ReturnType<typeof getMyPointBalance>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMyPointBalance<
  TData = Awaited<ReturnType<typeof getMyPointBalance>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMyPointBalance>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 사용자 포인트 잔액 조회
 */

export function useGetMyPointBalance<
  TData = Awaited<ReturnType<typeof getMyPointBalance>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMyPointBalance>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetMyPointBalanceQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * 사용자의 지난 포인트 적립/차감/사용 내역을 최신순으로 조회합니다.
 * @summary 사용자 포인트 이력 조회
 */
export type getMyPointTransactionHistoryResponse200 = {
  data: Blob;
  status: 200;
};

export type getMyPointTransactionHistoryResponseSuccess =
  getMyPointTransactionHistoryResponse200 & {
    headers: Headers;
  };
export type getMyPointTransactionHistoryResponse =
  getMyPointTransactionHistoryResponseSuccess;

export const getGetMyPointTransactionHistoryUrl = (
  params: GetMyPointTransactionHistoryParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/point/history?${stringifiedParams}`
    : `/api/v1/point/history`;
};

export const getMyPointTransactionHistory = async (
  params: GetMyPointTransactionHistoryParams,
  options?: RequestInit,
): Promise<getMyPointTransactionHistoryResponse> => {
  return customMutator<getMyPointTransactionHistoryResponse>(
    getGetMyPointTransactionHistoryUrl(params),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getGetMyPointTransactionHistoryQueryKey = (
  params?: GetMyPointTransactionHistoryParams,
) => {
  return [`/api/v1/point/history`, ...(params ? [params] : [])] as const;
};

export const getGetMyPointTransactionHistoryQueryOptions = <
  TData = Awaited<ReturnType<typeof getMyPointTransactionHistory>>,
  TError = unknown,
>(
  params: GetMyPointTransactionHistoryParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMyPointTransactionHistory>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customMutator>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetMyPointTransactionHistoryQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getMyPointTransactionHistory>>
  > = ({ signal }) =>
    getMyPointTransactionHistory(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getMyPointTransactionHistory>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetMyPointTransactionHistoryQueryResult = NonNullable<
  Awaited<ReturnType<typeof getMyPointTransactionHistory>>
>;
export type GetMyPointTransactionHistoryQueryError = unknown;

export function useGetMyPointTransactionHistory<
  TData = Awaited<ReturnType<typeof getMyPointTransactionHistory>>,
  TError = unknown,
>(
  params: GetMyPointTransactionHistoryParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMyPointTransactionHistory>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyPointTransactionHistory>>,
          TError,
          Awaited<ReturnType<typeof getMyPointTransactionHistory>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customMutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMyPointTransactionHistory<
  TData = Awaited<ReturnType<typeof getMyPointTransactionHistory>>,
  TError = unknown,
>(
  params: GetMyPointTransactionHistoryParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMyPointTransactionHistory>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyPointTransactionHistory>>,
          TError,
          Awaited<ReturnType<typeof getMyPointTransactionHistory>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMyPointTransactionHistory<
  TData = Awaited<ReturnType<typeof getMyPointTransactionHistory>>,
  TError = unknown,
>(
  params: GetMyPointTransactionHistoryParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMyPointTransactionHistory>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 사용자 포인트 이력 조회
 */

export function useGetMyPointTransactionHistory<
  TData = Awaited<ReturnType<typeof getMyPointTransactionHistory>>,
  TError = unknown,
>(
  params: GetMyPointTransactionHistoryParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMyPointTransactionHistory>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetMyPointTransactionHistoryQueryOptions(
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
