/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type { AutocompleteParams, SearchVideosParams } from ".././model";

import { customMutator } from "../../lib/mutator";

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * 키워드, 영상 타입, 태그를 조합하여 영상을 검색합니다. (주의: 깊은 페이징 방지를 위해 최대 10,000번째 결과까지만 조회 가능합니다.)
 * @summary 메인 영상 검색
 */
export type searchVideosResponse200 = {
  data: Blob;
  status: 200;
};

export type searchVideosResponseSuccess = searchVideosResponse200 & {
  headers: Headers;
};
export type searchVideosResponse = searchVideosResponseSuccess;

export const getSearchVideosUrl = (params?: SearchVideosParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/search?${stringifiedParams}`
    : `/api/v1/search`;
};

export const searchVideos = async (
  params?: SearchVideosParams,
  options?: RequestInit,
): Promise<searchVideosResponse> => {
  return customMutator<searchVideosResponse>(getSearchVideosUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getSearchVideosQueryKey = (params?: SearchVideosParams) => {
  return [`/api/v1/search`, ...(params ? [params] : [])] as const;
};

export const getSearchVideosQueryOptions = <
  TData = Awaited<ReturnType<typeof searchVideos>>,
  TError = unknown,
>(
  params?: SearchVideosParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof searchVideos>>, TError, TData>
    >;
    request?: SecondParameter<typeof customMutator>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getSearchVideosQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof searchVideos>>> = ({
    signal,
  }) => searchVideos(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof searchVideos>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type SearchVideosQueryResult = NonNullable<
  Awaited<ReturnType<typeof searchVideos>>
>;
export type SearchVideosQueryError = unknown;

export function useSearchVideos<
  TData = Awaited<ReturnType<typeof searchVideos>>,
  TError = unknown,
>(
  params: undefined | SearchVideosParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof searchVideos>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchVideos>>,
          TError,
          Awaited<ReturnType<typeof searchVideos>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customMutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSearchVideos<
  TData = Awaited<ReturnType<typeof searchVideos>>,
  TError = unknown,
>(
  params?: SearchVideosParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof searchVideos>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchVideos>>,
          TError,
          Awaited<ReturnType<typeof searchVideos>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSearchVideos<
  TData = Awaited<ReturnType<typeof searchVideos>>,
  TError = unknown,
>(
  params?: SearchVideosParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof searchVideos>>, TError, TData>
    >;
    request?: SecondParameter<typeof customMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 메인 영상 검색
 */

export function useSearchVideos<
  TData = Awaited<ReturnType<typeof searchVideos>>,
  TError = unknown,
>(
  params?: SearchVideosParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof searchVideos>>, TError, TData>
    >;
    request?: SecondParameter<typeof customMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getSearchVideosQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * 사용자가 검색창에 타이핑을 할 때 실시간으로 호출되어 추천 검색어(자동완성 목록)를 반환합니다.
 * @summary 검색어 자동완성 (실시간 추천)
 */
export type autocompleteResponse200 = {
  data: Blob;
  status: 200;
};

export type autocompleteResponseSuccess = autocompleteResponse200 & {
  headers: Headers;
};
export type autocompleteResponse = autocompleteResponseSuccess;

export const getAutocompleteUrl = (params: AutocompleteParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/search/autocomplete?${stringifiedParams}`
    : `/api/v1/search/autocomplete`;
};

export const autocomplete = async (
  params: AutocompleteParams,
  options?: RequestInit,
): Promise<autocompleteResponse> => {
  return customMutator<autocompleteResponse>(getAutocompleteUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getAutocompleteQueryKey = (params?: AutocompleteParams) => {
  return [`/api/v1/search/autocomplete`, ...(params ? [params] : [])] as const;
};

export const getAutocompleteQueryOptions = <
  TData = Awaited<ReturnType<typeof autocomplete>>,
  TError = unknown,
>(
  params: AutocompleteParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof autocomplete>>, TError, TData>
    >;
    request?: SecondParameter<typeof customMutator>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAutocompleteQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof autocomplete>>> = ({
    signal,
  }) => autocomplete(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof autocomplete>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type AutocompleteQueryResult = NonNullable<
  Awaited<ReturnType<typeof autocomplete>>
>;
export type AutocompleteQueryError = unknown;

export function useAutocomplete<
  TData = Awaited<ReturnType<typeof autocomplete>>,
  TError = unknown,
>(
  params: AutocompleteParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof autocomplete>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof autocomplete>>,
          TError,
          Awaited<ReturnType<typeof autocomplete>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customMutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAutocomplete<
  TData = Awaited<ReturnType<typeof autocomplete>>,
  TError = unknown,
>(
  params: AutocompleteParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof autocomplete>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof autocomplete>>,
          TError,
          Awaited<ReturnType<typeof autocomplete>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAutocomplete<
  TData = Awaited<ReturnType<typeof autocomplete>>,
  TError = unknown,
>(
  params: AutocompleteParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof autocomplete>>, TError, TData>
    >;
    request?: SecondParameter<typeof customMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 검색어 자동완성 (실시간 추천)
 */

export function useAutocomplete<
  TData = Awaited<ReturnType<typeof autocomplete>>,
  TError = unknown,
>(
  params: AutocompleteParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof autocomplete>>, TError, TData>
    >;
    request?: SecondParameter<typeof customMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getAutocompleteQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
