/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  ApiResponseContentUpdateResponse,
  ContentDeleteRequest,
  ContentUpdateMultipart,
  DeleteUserRequest,
  GetContentsParams,
  GetMyContentsParams,
  GetUsersParams,
  UserStatusUpdateRequest,
} from ".././model";

import { customMutator } from "../../lib/mutator";

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * 업로더가 특정 콘텐츠의 상세 정보를 조회합니다.
 * @summary 콘텐츠 상세 조회
 */
export type getContentDetailResponse200 = {
  data: Blob;
  status: 200;
};

export type getContentDetailResponseSuccess = getContentDetailResponse200 & {
  headers: Headers;
};
export type getContentDetailResponse = getContentDetailResponseSuccess;

export const getGetContentDetailUrl = (videoId: number) => {
  return `/api/v1/backoffice/contents/${videoId}`;
};

export const getContentDetail = async (
  videoId: number,
  options?: RequestInit,
): Promise<getContentDetailResponse> => {
  return customMutator<getContentDetailResponse>(
    getGetContentDetailUrl(videoId),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getGetContentDetailQueryKey = (videoId: number) => {
  return [`/api/v1/backoffice/contents/${videoId}`] as const;
};

export const getGetContentDetailQueryOptions = <
  TData = Awaited<ReturnType<typeof getContentDetail>>,
  TError = unknown,
>(
  videoId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getContentDetail>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customMutator>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetContentDetailQueryKey(videoId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getContentDetail>>
  > = ({ signal }) => getContentDetail(videoId, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!videoId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getContentDetail>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetContentDetailQueryResult = NonNullable<
  Awaited<ReturnType<typeof getContentDetail>>
>;
export type GetContentDetailQueryError = unknown;

export function useGetContentDetail<
  TData = Awaited<ReturnType<typeof getContentDetail>>,
  TError = unknown,
>(
  videoId: number,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getContentDetail>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getContentDetail>>,
          TError,
          Awaited<ReturnType<typeof getContentDetail>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customMutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetContentDetail<
  TData = Awaited<ReturnType<typeof getContentDetail>>,
  TError = unknown,
>(
  videoId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getContentDetail>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getContentDetail>>,
          TError,
          Awaited<ReturnType<typeof getContentDetail>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetContentDetail<
  TData = Awaited<ReturnType<typeof getContentDetail>>,
  TError = unknown,
>(
  videoId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getContentDetail>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 콘텐츠 상세 조회
 */

export function useGetContentDetail<
  TData = Awaited<ReturnType<typeof getContentDetail>>,
  TError = unknown,
>(
  videoId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getContentDetail>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetContentDetailQueryOptions(videoId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * 업로더가 콘텐츠의 썸네일 이미지 및 메타데이터를 수정합니다.
 * @summary 콘텐츠 수정
 */
export type updateContentResponse200 = {
  data: ApiResponseContentUpdateResponse;
  status: 200;
};

export type updateContentResponseSuccess = updateContentResponse200 & {
  headers: Headers;
};
export type updateContentResponse = updateContentResponseSuccess;

export const getUpdateContentUrl = (videoId: number) => {
  return `/api/v1/backoffice/contents/${videoId}`;
};

export const updateContent = async (
  videoId: number,
  contentUpdateMultipart: ContentUpdateMultipart,
  options?: RequestInit,
): Promise<updateContentResponse> => {
  const formData = new FormData();
  if (contentUpdateMultipart.image !== undefined) {
    formData.append(`image`, contentUpdateMultipart.image);
  }
  if (contentUpdateMultipart.data !== undefined) {
    formData.append(
      `data`,
      new Blob([JSON.stringify(contentUpdateMultipart.data)], {
        type: "application/json",
      }),
    );
  }

  return customMutator<updateContentResponse>(getUpdateContentUrl(videoId), {
    ...options,
    method: "PUT",
    body: formData,
  });
};

export const getUpdateContentMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateContent>>,
    TError,
    { videoId: number; data: ContentUpdateMultipart },
    TContext
  >;
  request?: SecondParameter<typeof customMutator>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateContent>>,
  TError,
  { videoId: number; data: ContentUpdateMultipart },
  TContext
> => {
  const mutationKey = ["updateContent"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateContent>>,
    { videoId: number; data: ContentUpdateMultipart }
  > = (props) => {
    const { videoId, data } = props ?? {};

    return updateContent(videoId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateContentMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateContent>>
>;
export type UpdateContentMutationBody = ContentUpdateMultipart;
export type UpdateContentMutationError = unknown;

/**
 * @summary 콘텐츠 수정
 */
export const useUpdateContent = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateContent>>,
      TError,
      { videoId: number; data: ContentUpdateMultipart },
      TContext
    >;
    request?: SecondParameter<typeof customMutator>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateContent>>,
  TError,
  { videoId: number; data: ContentUpdateMultipart },
  TContext
> => {
  return useMutation(getUpdateContentMutationOptions(options), queryClient);
};
/**
 * 어드민이 특정 유저의 활성/정지 상태를 변경합니다.
 * @summary 유저 상태 변경
 */
export type updateUserStatusResponse200 = {
  data: Blob;
  status: 200;
};

export type updateUserStatusResponseSuccess = updateUserStatusResponse200 & {
  headers: Headers;
};
export type updateUserStatusResponse = updateUserStatusResponseSuccess;

export const getUpdateUserStatusUrl = () => {
  return `/api/v1/backoffice/users/status`;
};

export const updateUserStatus = async (
  userStatusUpdateRequest: UserStatusUpdateRequest,
  options?: RequestInit,
): Promise<updateUserStatusResponse> => {
  return customMutator<updateUserStatusResponse>(getUpdateUserStatusUrl(), {
    ...options,
    method: "PATCH",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(userStatusUpdateRequest),
  });
};

export const getUpdateUserStatusMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateUserStatus>>,
    TError,
    { data: UserStatusUpdateRequest },
    TContext
  >;
  request?: SecondParameter<typeof customMutator>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateUserStatus>>,
  TError,
  { data: UserStatusUpdateRequest },
  TContext
> => {
  const mutationKey = ["updateUserStatus"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateUserStatus>>,
    { data: UserStatusUpdateRequest }
  > = (props) => {
    const { data } = props ?? {};

    return updateUserStatus(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateUserStatusMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateUserStatus>>
>;
export type UpdateUserStatusMutationBody = UserStatusUpdateRequest;
export type UpdateUserStatusMutationError = unknown;

/**
 * @summary 유저 상태 변경
 */
export const useUpdateUserStatus = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateUserStatus>>,
      TError,
      { data: UserStatusUpdateRequest },
      TContext
    >;
    request?: SecondParameter<typeof customMutator>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateUserStatus>>,
  TError,
  { data: UserStatusUpdateRequest },
  TContext
> => {
  return useMutation(getUpdateUserStatusMutationOptions(options), queryClient);
};
/**
 * 어드민이 역할(userRole) 및 키워드로 유저 목록을 페이지네이션으로 조회합니다.
 * @summary 유저 목록 조회
 */
export type getUsersResponse200 = {
  data: Blob;
  status: 200;
};

export type getUsersResponseSuccess = getUsersResponse200 & {
  headers: Headers;
};
export type getUsersResponse = getUsersResponseSuccess;

export const getGetUsersUrl = (params: GetUsersParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/backoffice/users?${stringifiedParams}`
    : `/api/v1/backoffice/users`;
};

export const getUsers = async (
  params: GetUsersParams,
  options?: RequestInit,
): Promise<getUsersResponse> => {
  return customMutator<getUsersResponse>(getGetUsersUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getGetUsersQueryKey = (params?: GetUsersParams) => {
  return [`/api/v1/backoffice/users`, ...(params ? [params] : [])] as const;
};

export const getGetUsersQueryOptions = <
  TData = Awaited<ReturnType<typeof getUsers>>,
  TError = unknown,
>(
  params: GetUsersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUsers>>, TError, TData>
    >;
    request?: SecondParameter<typeof customMutator>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetUsersQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getUsers>>> = ({
    signal,
  }) => getUsers(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getUsers>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetUsersQueryResult = NonNullable<
  Awaited<ReturnType<typeof getUsers>>
>;
export type GetUsersQueryError = unknown;

export function useGetUsers<
  TData = Awaited<ReturnType<typeof getUsers>>,
  TError = unknown,
>(
  params: GetUsersParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUsers>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUsers>>,
          TError,
          Awaited<ReturnType<typeof getUsers>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customMutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetUsers<
  TData = Awaited<ReturnType<typeof getUsers>>,
  TError = unknown,
>(
  params: GetUsersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUsers>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUsers>>,
          TError,
          Awaited<ReturnType<typeof getUsers>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetUsers<
  TData = Awaited<ReturnType<typeof getUsers>>,
  TError = unknown,
>(
  params: GetUsersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUsers>>, TError, TData>
    >;
    request?: SecondParameter<typeof customMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 유저 목록 조회
 */

export function useGetUsers<
  TData = Awaited<ReturnType<typeof getUsers>>,
  TError = unknown,
>(
  params: GetUsersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUsers>>, TError, TData>
    >;
    request?: SecondParameter<typeof customMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetUsersQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * 어드민이 특정 유저를 삭제합니다.
 * @summary 유저 삭제
 */
export type deleteUser1Response200 = {
  data: Blob;
  status: 200;
};

export type deleteUser1ResponseSuccess = deleteUser1Response200 & {
  headers: Headers;
};
export type deleteUser1Response = deleteUser1ResponseSuccess;

export const getDeleteUser1Url = () => {
  return `/api/v1/backoffice/users`;
};

export const deleteUser1 = async (
  deleteUserRequest: DeleteUserRequest,
  options?: RequestInit,
): Promise<deleteUser1Response> => {
  return customMutator<deleteUser1Response>(getDeleteUser1Url(), {
    ...options,
    method: "DELETE",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(deleteUserRequest),
  });
};

export const getDeleteUser1MutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteUser1>>,
    TError,
    { data: DeleteUserRequest },
    TContext
  >;
  request?: SecondParameter<typeof customMutator>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteUser1>>,
  TError,
  { data: DeleteUserRequest },
  TContext
> => {
  const mutationKey = ["deleteUser1"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteUser1>>,
    { data: DeleteUserRequest }
  > = (props) => {
    const { data } = props ?? {};

    return deleteUser1(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteUser1MutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteUser1>>
>;
export type DeleteUser1MutationBody = DeleteUserRequest;
export type DeleteUser1MutationError = unknown;

/**
 * @summary 유저 삭제
 */
export const useDeleteUser1 = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteUser1>>,
      TError,
      { data: DeleteUserRequest },
      TContext
    >;
    request?: SecondParameter<typeof customMutator>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteUser1>>,
  TError,
  { data: DeleteUserRequest },
  TContext
> => {
  return useMutation(getDeleteUser1MutationOptions(options), queryClient);
};
/**
 * 로그인한 업로더 본인의 콘텐츠 목록을 페이지네이션으로 조회합니다.
 * @summary 업로더 콘텐츠 목록 조회
 */
export type getMyContentsResponse200 = {
  data: Blob;
  status: 200;
};

export type getMyContentsResponseSuccess = getMyContentsResponse200 & {
  headers: Headers;
};
export type getMyContentsResponse = getMyContentsResponseSuccess;

export const getGetMyContentsUrl = (params?: GetMyContentsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/backoffice/uploader/contents?${stringifiedParams}`
    : `/api/v1/backoffice/uploader/contents`;
};

export const getMyContents = async (
  params?: GetMyContentsParams,
  options?: RequestInit,
): Promise<getMyContentsResponse> => {
  return customMutator<getMyContentsResponse>(getGetMyContentsUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getGetMyContentsQueryKey = (params?: GetMyContentsParams) => {
  return [
    `/api/v1/backoffice/uploader/contents`,
    ...(params ? [params] : []),
  ] as const;
};

export const getGetMyContentsQueryOptions = <
  TData = Awaited<ReturnType<typeof getMyContents>>,
  TError = unknown,
>(
  params?: GetMyContentsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMyContents>>, TError, TData>
    >;
    request?: SecondParameter<typeof customMutator>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetMyContentsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMyContents>>> = ({
    signal,
  }) => getMyContents(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getMyContents>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetMyContentsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getMyContents>>
>;
export type GetMyContentsQueryError = unknown;

export function useGetMyContents<
  TData = Awaited<ReturnType<typeof getMyContents>>,
  TError = unknown,
>(
  params: undefined | GetMyContentsParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMyContents>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyContents>>,
          TError,
          Awaited<ReturnType<typeof getMyContents>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customMutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMyContents<
  TData = Awaited<ReturnType<typeof getMyContents>>,
  TError = unknown,
>(
  params?: GetMyContentsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMyContents>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyContents>>,
          TError,
          Awaited<ReturnType<typeof getMyContents>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMyContents<
  TData = Awaited<ReturnType<typeof getMyContents>>,
  TError = unknown,
>(
  params?: GetMyContentsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMyContents>>, TError, TData>
    >;
    request?: SecondParameter<typeof customMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 업로더 콘텐츠 목록 조회
 */

export function useGetMyContents<
  TData = Awaited<ReturnType<typeof getMyContents>>,
  TError = unknown,
>(
  params?: GetMyContentsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMyContents>>, TError, TData>
    >;
    request?: SecondParameter<typeof customMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetMyContentsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * 어드민이 전체 콘텐츠 목록을 키워드 검색 및 페이지네이션으로 조회합니다.
 * @summary 어드민 콘텐츠 목록 조회
 */
export type getContentsResponse200 = {
  data: Blob;
  status: 200;
};

export type getContentsResponseSuccess = getContentsResponse200 & {
  headers: Headers;
};
export type getContentsResponse = getContentsResponseSuccess;

export const getGetContentsUrl = (params?: GetContentsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/backoffice/admin/contents?${stringifiedParams}`
    : `/api/v1/backoffice/admin/contents`;
};

export const getContents = async (
  params?: GetContentsParams,
  options?: RequestInit,
): Promise<getContentsResponse> => {
  return customMutator<getContentsResponse>(getGetContentsUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getGetContentsQueryKey = (params?: GetContentsParams) => {
  return [
    `/api/v1/backoffice/admin/contents`,
    ...(params ? [params] : []),
  ] as const;
};

export const getGetContentsQueryOptions = <
  TData = Awaited<ReturnType<typeof getContents>>,
  TError = unknown,
>(
  params?: GetContentsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getContents>>, TError, TData>
    >;
    request?: SecondParameter<typeof customMutator>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetContentsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getContents>>> = ({
    signal,
  }) => getContents(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getContents>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetContentsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getContents>>
>;
export type GetContentsQueryError = unknown;

export function useGetContents<
  TData = Awaited<ReturnType<typeof getContents>>,
  TError = unknown,
>(
  params: undefined | GetContentsParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getContents>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getContents>>,
          TError,
          Awaited<ReturnType<typeof getContents>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customMutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetContents<
  TData = Awaited<ReturnType<typeof getContents>>,
  TError = unknown,
>(
  params?: GetContentsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getContents>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getContents>>,
          TError,
          Awaited<ReturnType<typeof getContents>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetContents<
  TData = Awaited<ReturnType<typeof getContents>>,
  TError = unknown,
>(
  params?: GetContentsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getContents>>, TError, TData>
    >;
    request?: SecondParameter<typeof customMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 어드민 콘텐츠 목록 조회
 */

export function useGetContents<
  TData = Awaited<ReturnType<typeof getContents>>,
  TError = unknown,
>(
  params?: GetContentsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getContents>>, TError, TData>
    >;
    request?: SecondParameter<typeof customMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetContentsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * 업로더는 본인 콘텐츠만, 어드민은 모든 콘텐츠를 삭제할 수 있습니다.
 * @summary 콘텐츠 삭제
 */
export type deleteContentResponse200 = {
  data: Blob;
  status: 200;
};

export type deleteContentResponseSuccess = deleteContentResponse200 & {
  headers: Headers;
};
export type deleteContentResponse = deleteContentResponseSuccess;

export const getDeleteContentUrl = () => {
  return `/api/v1/backoffice/contents`;
};

export const deleteContent = async (
  contentDeleteRequest: ContentDeleteRequest,
  options?: RequestInit,
): Promise<deleteContentResponse> => {
  return customMutator<deleteContentResponse>(getDeleteContentUrl(), {
    ...options,
    method: "DELETE",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(contentDeleteRequest),
  });
};

export const getDeleteContentMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteContent>>,
    TError,
    { data: ContentDeleteRequest },
    TContext
  >;
  request?: SecondParameter<typeof customMutator>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteContent>>,
  TError,
  { data: ContentDeleteRequest },
  TContext
> => {
  const mutationKey = ["deleteContent"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteContent>>,
    { data: ContentDeleteRequest }
  > = (props) => {
    const { data } = props ?? {};

    return deleteContent(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteContentMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteContent>>
>;
export type DeleteContentMutationBody = ContentDeleteRequest;
export type DeleteContentMutationError = unknown;

/**
 * @summary 콘텐츠 삭제
 */
export const useDeleteContent = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteContent>>,
      TError,
      { data: ContentDeleteRequest },
      TContext
    >;
    request?: SecondParameter<typeof customMutator>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteContent>>,
  TError,
  { data: ContentDeleteRequest },
  TContext
> => {
  return useMutation(getDeleteContentMutationOptions(options), queryClient);
};
