/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { AdminContentResponseVisibility } from './adminContentResponseVisibility';

export interface AdminContentResponse {
  videoId?: string;
  thumbnailUrl?: string;
  title?: string;
  description?: string;
  otherVideoUrl?: string;
  viewCount?: number;
  likeCount?: number;
  dislikeCount?: number;
  commentCount?: number;
  visibility?: AdminContentResponseVisibility;
  createdAt?: string;
}
