/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type AdminUserResponseBanStatus =
  (typeof AdminUserResponseBanStatus)[keyof typeof AdminUserResponseBanStatus];

export const AdminUserResponseBanStatus = {
  ACTIVE: "ACTIVE",
  DEACTIVATED: "DEACTIVATED",
  SUSPENDED_7: "SUSPENDED_7",
  SUSPENDED_15: "SUSPENDED_15",
  SUSPENDED_30: "SUSPENDED_30",
  DELETED: "DELETED",
} as const;
