/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type ApiResponseAdResponseResult = typeof ApiResponseAdResponseResult[keyof typeof ApiResponseAdResponseResult];


export const ApiResponseAdResponseResult = {
  SUCCESS: 'SUCCESS',
  ERROR: 'ERROR',
} as const;
