/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ApiResponseSubscriptionResponseResult } from './apiResponseSubscriptionResponseResult';
import type { ErrorMessage } from './errorMessage';
import type { SubscriptionResponse } from './subscriptionResponse';

export interface ApiResponseSubscriptionResponse {
  result?: ApiResponseSubscriptionResponseResult;
  data?: SubscriptionResponse;
  error?: ErrorMessage;
}
