/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type ApiResponseUserResponseResult = typeof ApiResponseUserResponseResult[keyof typeof ApiResponseUserResponseResult];


export const ApiResponseUserResponseResult = {
  SUCCESS: 'SUCCESS',
  ERROR: 'ERROR',
} as const;
