/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ApiResponseListDiscountHistoryResponseResult } from './apiResponseListDiscountHistoryResponseResult';
import type { DiscountHistoryResponse } from './discountHistoryResponse';
import type { ErrorMessage } from './errorMessage';

export interface ApiResponseListDiscountHistoryResponse {
  result?: ApiResponseListDiscountHistoryResponseResult;
  data?: DiscountHistoryResponse[];
  error?: ErrorMessage;
}
