/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ApiResponseBackofficeLoginResponseResult } from './apiResponseBackofficeLoginResponseResult';
import type { BackofficeLoginResponse } from './backofficeLoginResponse';
import type { ErrorMessage } from './errorMessage';

export interface ApiResponseBackofficeLoginResponse {
  result?: ApiResponseBackofficeLoginResponseResult;
  data?: BackofficeLoginResponse;
  error?: ErrorMessage;
}
