/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type ApiResponseListStringResult = typeof ApiResponseListStringResult[keyof typeof ApiResponseListStringResult];


export const ApiResponseListStringResult = {
  SUCCESS: 'SUCCESS',
  ERROR: 'ERROR',
} as const;
