/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ApiResponseListTagWatchStatsResponseResult } from "./apiResponseListTagWatchStatsResponseResult";
import type { ErrorMessage } from "./errorMessage";
import type { TagWatchStatsResponse } from "./tagWatchStatsResponse";

export interface ApiResponseListTagWatchStatsResponse {
  result?: ApiResponseListTagWatchStatsResponseResult;
  data?: TagWatchStatsResponse[];
  error?: ErrorMessage;
}
