/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type ApiResponseVoidResult = typeof ApiResponseVoidResult[keyof typeof ApiResponseVoidResult];


export const ApiResponseVoidResult = {
  SUCCESS: 'SUCCESS',
  ERROR: 'ERROR',
} as const;
