/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ApiResponseListPlanInfoResult } from "./apiResponseListPlanInfoResult";
import type { ErrorMessage } from "./errorMessage";
import type { PlanInfo } from "./planInfo";

export interface ApiResponseListPlanInfo {
  result?: ApiResponseListPlanInfoResult;
  data?: PlanInfo[];
  error?: ErrorMessage;
}
