/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ApiResponseVoidData } from "./apiResponseVoidData";
import type { ApiResponseVoidResult } from "./apiResponseVoidResult";
import type { ErrorMessage } from "./errorMessage";

export interface ApiResponseVoid {
  result?: ApiResponseVoidResult;
  data?: ApiResponseVoidData;
  error?: ErrorMessage;
}
