/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type ApiResponseWatchHistoryResponseResult = typeof ApiResponseWatchHistoryResponseResult[keyof typeof ApiResponseWatchHistoryResponseResult];


export const ApiResponseWatchHistoryResponseResult = {
  SUCCESS: 'SUCCESS',
  ERROR: 'ERROR',
} as const;
