/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type ApiResponseInteractionStatusResponseDtoResult = typeof ApiResponseInteractionStatusResponseDtoResult[keyof typeof ApiResponseInteractionStatusResponseDtoResult];


export const ApiResponseInteractionStatusResponseDtoResult = {
  SUCCESS: 'SUCCESS',
  ERROR: 'ERROR',
} as const;
