/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type ApiResponseBookmarkPageResponseResult =
  (typeof ApiResponseBookmarkPageResponseResult)[keyof typeof ApiResponseBookmarkPageResponseResult];

export const ApiResponseBookmarkPageResponseResult = {
  SUCCESS: "SUCCESS",
  ERROR: "ERROR",
} as const;
