/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ApiResponseListParentTagWithChildResponseResult } from "./apiResponseListParentTagWithChildResponseResult";
import type { ErrorMessage } from "./errorMessage";
import type { ParentTagWithChildResponse } from "./parentTagWithChildResponse";

export interface ApiResponseListParentTagWithChildResponse {
  result?: ApiResponseListParentTagWithChildResponseResult;
  data?: ParentTagWithChildResponse[];
  error?: ErrorMessage;
}
