/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type ApiResponseMultipartInitResponseResult = typeof ApiResponseMultipartInitResponseResult[keyof typeof ApiResponseMultipartInitResponseResult];


export const ApiResponseMultipartInitResponseResult = {
  SUCCESS: 'SUCCESS',
  ERROR: 'ERROR',
} as const;
