/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type ApiResponseLoginResponseResult = typeof ApiResponseLoginResponseResult[keyof typeof ApiResponseLoginResponseResult];


export const ApiResponseLoginResponseResult = {
  SUCCESS: 'SUCCESS',
  ERROR: 'ERROR',
} as const;
