/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ApiResponseListRankingResponseResult } from "./apiResponseListRankingResponseResult";
import type { ErrorMessage } from "./errorMessage";
import type { RankingResponse } from "./rankingResponse";

export interface ApiResponseListRankingResponse {
  result?: ApiResponseListRankingResponseResult;
  data?: RankingResponse[];
  error?: ErrorMessage;
}
