/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ApiResponseListPointTransactionHistoryResponseResult } from "./apiResponseListPointTransactionHistoryResponseResult";
import type { ErrorMessage } from "./errorMessage";
import type { PointTransactionHistoryResponse } from "./pointTransactionHistoryResponse";

export interface ApiResponseListPointTransactionHistoryResponse {
  result?: ApiResponseListPointTransactionHistoryResponseResult;
  data?: PointTransactionHistoryResponse[];
  error?: ErrorMessage;
}
