/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ApiResponseLoginResponseResult } from './apiResponseLoginResponseResult';
import type { ErrorMessage } from './errorMessage';
import type { LoginResponse } from './loginResponse';

export interface ApiResponseLoginResponse {
  result?: ApiResponseLoginResponseResult;
  data?: LoginResponse;
  error?: ErrorMessage;
}
