/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type ApiResponseObjectResult = typeof ApiResponseObjectResult[keyof typeof ApiResponseObjectResult];


export const ApiResponseObjectResult = {
  SUCCESS: 'SUCCESS',
  ERROR: 'ERROR',
} as const;
