/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type ApiResponseCommentPageResponseResult =
  (typeof ApiResponseCommentPageResponseResult)[keyof typeof ApiResponseCommentPageResponseResult];

export const ApiResponseCommentPageResponseResult = {
  SUCCESS: "SUCCESS",
  ERROR: "ERROR",
} as const;
