/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type ApiResponseListTagVideoResponseResult = typeof ApiResponseListTagVideoResponseResult[keyof typeof ApiResponseListTagVideoResponseResult];


export const ApiResponseListTagVideoResponseResult = {
  SUCCESS: 'SUCCESS',
  ERROR: 'ERROR',
} as const;
