/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type ApiResponseContentDetailResponseResult =
  (typeof ApiResponseContentDetailResponseResult)[keyof typeof ApiResponseContentDetailResponseResult];

export const ApiResponseContentDetailResponseResult = {
  SUCCESS: "SUCCESS",
  ERROR: "ERROR",
} as const;
