/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ApiResponseBooleanResult } from "./apiResponseBooleanResult";
import type { ErrorMessage } from "./errorMessage";

export interface ApiResponseBoolean {
  result?: ApiResponseBooleanResult;
  data?: boolean;
  error?: ErrorMessage;
}
