/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ApiResponsePageResponseUploaderContentResponseResult } from './apiResponsePageResponseUploaderContentResponseResult';
import type { ErrorMessage } from './errorMessage';
import type { PageResponseUploaderContentResponse } from './pageResponseUploaderContentResponse';

export interface ApiResponsePageResponseUploaderContentResponse {
  result?: ApiResponsePageResponseUploaderContentResponseResult;
  data?: PageResponseUploaderContentResponse;
  error?: ErrorMessage;
}
