/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type ApiResponsePageResponseAdminUserResponseResult =
  (typeof ApiResponsePageResponseAdminUserResponseResult)[keyof typeof ApiResponsePageResponseAdminUserResponseResult];

export const ApiResponsePageResponseAdminUserResponseResult = {
  SUCCESS: "SUCCESS",
  ERROR: "ERROR",
} as const;
