/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ApiResponseCommentPageResponseResult } from './apiResponseCommentPageResponseResult';
import type { CommentPageResponse } from './commentPageResponse';
import type { ErrorMessage } from './errorMessage';

export interface ApiResponseCommentPageResponse {
  result?: ApiResponseCommentPageResponseResult;
  data?: CommentPageResponse;
  error?: ErrorMessage;
}
