/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type ApiResponseListPointTransactionHistoryResponseResult = typeof ApiResponseListPointTransactionHistoryResponseResult[keyof typeof ApiResponseListPointTransactionHistoryResponseResult];


export const ApiResponseListPointTransactionHistoryResponseResult = {
  SUCCESS: 'SUCCESS',
  ERROR: 'ERROR',
} as const;
