/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ApiResponseBookmarkPageResponseResult } from "./apiResponseBookmarkPageResponseResult";
import type { BookmarkPageResponse } from "./bookmarkPageResponse";
import type { ErrorMessage } from "./errorMessage";

export interface ApiResponseBookmarkPageResponse {
  result?: ApiResponseBookmarkPageResponseResult;
  data?: BookmarkPageResponse;
  error?: ErrorMessage;
}
