/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ApiResponseUserStatusUpdateResponseResult } from './apiResponseUserStatusUpdateResponseResult';
import type { ErrorMessage } from './errorMessage';
import type { UserStatusUpdateResponse } from './userStatusUpdateResponse';

export interface ApiResponseUserStatusUpdateResponse {
  result?: ApiResponseUserStatusUpdateResponseResult;
  data?: UserStatusUpdateResponse;
  error?: ErrorMessage;
}
