/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ApiResponseTokenRefreshResponseResult } from './apiResponseTokenRefreshResponseResult';
import type { ErrorMessage } from './errorMessage';
import type { TokenRefreshResponse } from './tokenRefreshResponse';

export interface ApiResponseTokenRefreshResponse {
  result?: ApiResponseTokenRefreshResponseResult;
  data?: TokenRefreshResponse;
  error?: ErrorMessage;
}
