/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ApiResponseListPointPolicyResponseResult } from "./apiResponseListPointPolicyResponseResult";
import type { ErrorMessage } from "./errorMessage";
import type { PointPolicyResponse } from "./pointPolicyResponse";

export interface ApiResponseListPointPolicyResponse {
  result?: ApiResponseListPointPolicyResponseResult;
  data?: PointPolicyResponse[];
  error?: ErrorMessage;
}
