/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ApiResponseWatchHistoryPageResponseResult } from './apiResponseWatchHistoryPageResponseResult';
import type { ErrorMessage } from './errorMessage';
import type { WatchHistoryPageResponse } from './watchHistoryPageResponse';

export interface ApiResponseWatchHistoryPageResponse {
  result?: ApiResponseWatchHistoryPageResponseResult;
  data?: WatchHistoryPageResponse;
  error?: ErrorMessage;
}
