/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type ApiResponseListPlanInfoResult =
  (typeof ApiResponseListPlanInfoResult)[keyof typeof ApiResponseListPlanInfoResult];

export const ApiResponseListPlanInfoResult = {
  SUCCESS: "SUCCESS",
  ERROR: "ERROR",
} as const;
