/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ApiResponseWatchHistoryResponseResult } from './apiResponseWatchHistoryResponseResult';
import type { ErrorMessage } from './errorMessage';
import type { WatchHistoryResponse } from './watchHistoryResponse';

export interface ApiResponseWatchHistoryResponse {
  result?: ApiResponseWatchHistoryResponseResult;
  data?: WatchHistoryResponse;
  error?: ErrorMessage;
}
