/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { AdResponse } from './adResponse';
import type { ApiResponseAdResponseResult } from './apiResponseAdResponseResult';
import type { ErrorMessage } from './errorMessage';

export interface ApiResponseAdResponse {
  result?: ApiResponseAdResponseResult;
  data?: AdResponse;
  error?: ErrorMessage;
}
