/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ApiResponseMyCommentResponseResult } from "./apiResponseMyCommentResponseResult";
import type { ErrorMessage } from "./errorMessage";
import type { MyCommentResponse } from "./myCommentResponse";

export interface ApiResponseMyCommentResponse {
  result?: ApiResponseMyCommentResponseResult;
  data?: MyCommentResponse;
  error?: ErrorMessage;
}
