/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type ApiResponseListTagWatchStatsResponseResult =
  (typeof ApiResponseListTagWatchStatsResponseResult)[keyof typeof ApiResponseListTagWatchStatsResponseResult];

export const ApiResponseListTagWatchStatsResponseResult = {
  SUCCESS: "SUCCESS",
  ERROR: "ERROR",
} as const;
