/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type ApiResponseBooleanResult = typeof ApiResponseBooleanResult[keyof typeof ApiResponseBooleanResult];


export const ApiResponseBooleanResult = {
  SUCCESS: 'SUCCESS',
  ERROR: 'ERROR',
} as const;
