/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ApiResponseContentDetailResponseResult } from "./apiResponseContentDetailResponseResult";
import type { ContentDetailResponse } from "./contentDetailResponse";
import type { ErrorMessage } from "./errorMessage";

export interface ApiResponseContentDetailResponse {
  result?: ApiResponseContentDetailResponseResult;
  data?: ContentDetailResponse;
  error?: ErrorMessage;
}
