/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ApiResponseSliceResponseVideoFeedResponseDtoResult } from './apiResponseSliceResponseVideoFeedResponseDtoResult';
import type { ErrorMessage } from './errorMessage';
import type { SliceResponseVideoFeedResponseDto } from './sliceResponseVideoFeedResponseDto';

export interface ApiResponseSliceResponseVideoFeedResponseDto {
  result?: ApiResponseSliceResponseVideoFeedResponseDtoResult;
  data?: SliceResponseVideoFeedResponseDto;
  error?: ErrorMessage;
}
