/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type ApiResponseStringResult =
  (typeof ApiResponseStringResult)[keyof typeof ApiResponseStringResult];

export const ApiResponseStringResult = {
  SUCCESS: "SUCCESS",
  ERROR: "ERROR",
} as const;
