/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type ApiResponseVideoInfoResponseResult = typeof ApiResponseVideoInfoResponseResult[keyof typeof ApiResponseVideoInfoResponseResult];


export const ApiResponseVideoInfoResponseResult = {
  SUCCESS: 'SUCCESS',
  ERROR: 'ERROR',
} as const;
