/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ApiResponseUserPointBalanceResponseResult } from "./apiResponseUserPointBalanceResponseResult";
import type { ErrorMessage } from "./errorMessage";
import type { UserPointBalanceResponse } from "./userPointBalanceResponse";

export interface ApiResponseUserPointBalanceResponse {
  result?: ApiResponseUserPointBalanceResponseResult;
  data?: UserPointBalanceResponse;
  error?: ErrorMessage;
}
