/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type ApiResponseBookmarkStatusResponseDtoResult = typeof ApiResponseBookmarkStatusResponseDtoResult[keyof typeof ApiResponseBookmarkStatusResponseDtoResult];


export const ApiResponseBookmarkStatusResponseDtoResult = {
  SUCCESS: 'SUCCESS',
  ERROR: 'ERROR',
} as const;
