/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ApiResponsePageVideoSearchResponseResult } from "./apiResponsePageVideoSearchResponseResult";
import type { ErrorMessage } from "./errorMessage";
import type { PageVideoSearchResponse } from "./pageVideoSearchResponse";

export interface ApiResponsePageVideoSearchResponse {
  result?: ApiResponsePageVideoSearchResponseResult;
  data?: PageVideoSearchResponse;
  error?: ErrorMessage;
}
