/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ApiResponseStringResult } from './apiResponseStringResult';
import type { ErrorMessage } from './errorMessage';

export interface ApiResponseString {
  result?: ApiResponseStringResult;
  data?: string;
  error?: ErrorMessage;
}
