/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type ApiResponseUserStatusUpdateResponseResult =
  (typeof ApiResponseUserStatusUpdateResponseResult)[keyof typeof ApiResponseUserStatusUpdateResponseResult];

export const ApiResponseUserStatusUpdateResponseResult = {
  SUCCESS: "SUCCESS",
  ERROR: "ERROR",
} as const;
