/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type ApiResponseTokenRefreshResponseResult = typeof ApiResponseTokenRefreshResponseResult[keyof typeof ApiResponseTokenRefreshResponseResult];


export const ApiResponseTokenRefreshResponseResult = {
  SUCCESS: 'SUCCESS',
  ERROR: 'ERROR',
} as const;
