/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type ApiResponseListRankingResponseResult = typeof ApiResponseListRankingResponseResult[keyof typeof ApiResponseListRankingResponseResult];


export const ApiResponseListRankingResponseResult = {
  SUCCESS: 'SUCCESS',
  ERROR: 'ERROR',
} as const;
