/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type ApiResponseWatchHistoryPageResponseResult =
  (typeof ApiResponseWatchHistoryPageResponseResult)[keyof typeof ApiResponseWatchHistoryPageResponseResult];

export const ApiResponseWatchHistoryPageResponseResult = {
  SUCCESS: "SUCCESS",
  ERROR: "ERROR",
} as const;
