/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ApiResponseUserDetailResponseResult } from './apiResponseUserDetailResponseResult';
import type { ErrorMessage } from './errorMessage';
import type { UserDetailResponse } from './userDetailResponse';

export interface ApiResponseUserDetailResponse {
  result?: ApiResponseUserDetailResponseResult;
  data?: UserDetailResponse;
  error?: ErrorMessage;
}
