/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ApiResponsePageResponseAdminContentResponseResult } from "./apiResponsePageResponseAdminContentResponseResult";
import type { ErrorMessage } from "./errorMessage";
import type { PageResponseAdminContentResponse } from "./pageResponseAdminContentResponse";

export interface ApiResponsePageResponseAdminContentResponse {
  result?: ApiResponsePageResponseAdminContentResponseResult;
  data?: PageResponseAdminContentResponse;
  error?: ErrorMessage;
}
