/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type ApiResponsePageResponseAdminContentResponseResult =
  (typeof ApiResponsePageResponseAdminContentResponseResult)[keyof typeof ApiResponsePageResponseAdminContentResponseResult];

export const ApiResponsePageResponseAdminContentResponseResult = {
  SUCCESS: "SUCCESS",
  ERROR: "ERROR",
} as const;
