/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type ApiResponseContentUpdateResponseResult =
  (typeof ApiResponseContentUpdateResponseResult)[keyof typeof ApiResponseContentUpdateResponseResult];

export const ApiResponseContentUpdateResponseResult = {
  SUCCESS: "SUCCESS",
  ERROR: "ERROR",
} as const;
