/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ApiResponseListTagVideoResponseResult } from './apiResponseListTagVideoResponseResult';
import type { ErrorMessage } from './errorMessage';
import type { TagVideoResponse } from './tagVideoResponse';

export interface ApiResponseListTagVideoResponse {
  result?: ApiResponseListTagVideoResponseResult;
  data?: TagVideoResponse[];
  error?: ErrorMessage;
}
