/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ApiResponseBookmarkSummaryResponseResult } from "./apiResponseBookmarkSummaryResponseResult";
import type { BookmarkSummaryResponse } from "./bookmarkSummaryResponse";
import type { ErrorMessage } from "./errorMessage";

export interface ApiResponseBookmarkSummaryResponse {
  result?: ApiResponseBookmarkSummaryResponseResult;
  data?: BookmarkSummaryResponse;
  error?: ErrorMessage;
}
