/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ApiResponseMultipartInitResponseResult } from './apiResponseMultipartInitResponseResult';
import type { ErrorMessage } from './errorMessage';
import type { MultipartInitResponse } from './multipartInitResponse';

export interface ApiResponseMultipartInitResponse {
  result?: ApiResponseMultipartInitResponseResult;
  data?: MultipartInitResponse;
  error?: ErrorMessage;
}
