/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ApiResponseRegisterResponseResult } from './apiResponseRegisterResponseResult';
import type { ErrorMessage } from './errorMessage';
import type { RegisterResponse } from './registerResponse';

export interface ApiResponseRegisterResponse {
  result?: ApiResponseRegisterResponseResult;
  data?: RegisterResponse;
  error?: ErrorMessage;
}
