/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type ApiResponseListPointPolicyResponseResult =
  (typeof ApiResponseListPointPolicyResponseResult)[keyof typeof ApiResponseListPointPolicyResponseResult];

export const ApiResponseListPointPolicyResponseResult = {
  SUCCESS: "SUCCESS",
  ERROR: "ERROR",
} as const;
