/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ApiResponseListStringResult } from "./apiResponseListStringResult";
import type { ErrorMessage } from "./errorMessage";

export interface ApiResponseListString {
  result?: ApiResponseListStringResult;
  data?: string[];
  error?: ErrorMessage;
}
