/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type ApiResponsePageVideoSearchResponseResult =
  (typeof ApiResponsePageVideoSearchResponseResult)[keyof typeof ApiResponsePageVideoSearchResponseResult];

export const ApiResponsePageVideoSearchResponseResult = {
  SUCCESS: "SUCCESS",
  ERROR: "ERROR",
} as const;
