/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ApiResponseVideoInfoResponseResult } from './apiResponseVideoInfoResponseResult';
import type { ErrorMessage } from './errorMessage';
import type { VideoInfoResponse } from './videoInfoResponse';

export interface ApiResponseVideoInfoResponse {
  result?: ApiResponseVideoInfoResponseResult;
  data?: VideoInfoResponse;
  error?: ErrorMessage;
}
