/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ApiResponseBookmarkStatusResponseDtoResult } from './apiResponseBookmarkStatusResponseDtoResult';
import type { BookmarkStatusResponseDto } from './bookmarkStatusResponseDto';
import type { ErrorMessage } from './errorMessage';

export interface ApiResponseBookmarkStatusResponseDto {
  result?: ApiResponseBookmarkStatusResponseDtoResult;
  data?: BookmarkStatusResponseDto;
  error?: ErrorMessage;
}
