/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ApiResponseContentUpdateResponseResult } from "./apiResponseContentUpdateResponseResult";
import type { ContentUpdateResponse } from "./contentUpdateResponse";
import type { ErrorMessage } from "./errorMessage";

export interface ApiResponseContentUpdateResponse {
  result?: ApiResponseContentUpdateResponseResult;
  data?: ContentUpdateResponse;
  error?: ErrorMessage;
}
