/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type ApiResponseListTagScoreDtoResult = typeof ApiResponseListTagScoreDtoResult[keyof typeof ApiResponseListTagScoreDtoResult];


export const ApiResponseListTagScoreDtoResult = {
  SUCCESS: 'SUCCESS',
  ERROR: 'ERROR',
} as const;
