/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type ApiResponsePlayResponseResult =
  (typeof ApiResponsePlayResponseResult)[keyof typeof ApiResponsePlayResponseResult];

export const ApiResponsePlayResponseResult = {
  SUCCESS: "SUCCESS",
  ERROR: "ERROR",
} as const;
