/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ApiResponseUserResponseResult } from './apiResponseUserResponseResult';
import type { ErrorMessage } from './errorMessage';
import type { UserResponse } from './userResponse';

export interface ApiResponseUserResponse {
  result?: ApiResponseUserResponseResult;
  data?: UserResponse;
  error?: ErrorMessage;
}
