/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type ApiResponseSliceResponseVideoFeedResponseDtoResult =
  (typeof ApiResponseSliceResponseVideoFeedResponseDtoResult)[keyof typeof ApiResponseSliceResponseVideoFeedResponseDtoResult];

export const ApiResponseSliceResponseVideoFeedResponseDtoResult = {
  SUCCESS: "SUCCESS",
  ERROR: "ERROR",
} as const;
