/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type ApiResponseUserPointBalanceResponseResult = typeof ApiResponseUserPointBalanceResponseResult[keyof typeof ApiResponseUserPointBalanceResponseResult];


export const ApiResponseUserPointBalanceResponseResult = {
  SUCCESS: 'SUCCESS',
  ERROR: 'ERROR',
} as const;
