/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type ApiResponseListChildTagResponseResult = typeof ApiResponseListChildTagResponseResult[keyof typeof ApiResponseListChildTagResponseResult];


export const ApiResponseListChildTagResponseResult = {
  SUCCESS: 'SUCCESS',
  ERROR: 'ERROR',
} as const;
