/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ApiResponsePageResponseAdminUserResponseResult } from './apiResponsePageResponseAdminUserResponseResult';
import type { ErrorMessage } from './errorMessage';
import type { PageResponseAdminUserResponse } from './pageResponseAdminUserResponse';

export interface ApiResponsePageResponseAdminUserResponse {
  result?: ApiResponsePageResponseAdminUserResponseResult;
  data?: PageResponseAdminUserResponse;
  error?: ErrorMessage;
}
