/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ApiResponseListChildTagResponseResult } from "./apiResponseListChildTagResponseResult";
import type { ChildTagResponse } from "./childTagResponse";
import type { ErrorMessage } from "./errorMessage";

export interface ApiResponseListChildTagResponse {
  result?: ApiResponseListChildTagResponseResult;
  data?: ChildTagResponse[];
  error?: ErrorMessage;
}
