/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ApiResponseInteractionStatusResponseDtoResult } from "./apiResponseInteractionStatusResponseDtoResult";
import type { ErrorMessage } from "./errorMessage";
import type { InteractionStatusResponseDto } from "./interactionStatusResponseDto";

export interface ApiResponseInteractionStatusResponseDto {
  result?: ApiResponseInteractionStatusResponseDtoResult;
  data?: InteractionStatusResponseDto;
  error?: ErrorMessage;
}
