/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type AutocompleteParams = {
  /**
   * 현재까지 입력된 부분 검색어
   */
  keyword: string;
};
