/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type BackofficeLoginResponseRole = typeof BackofficeLoginResponseRole[keyof typeof BackofficeLoginResponseRole];


export const BackofficeLoginResponseRole = {
  VIEWER: 'VIEWER',
  UPLOADER: 'UPLOADER',
  ADMIN: 'ADMIN',
} as const;
