/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { BookmarkListResponse } from './bookmarkListResponse';

export interface BookmarkPageResponse {
  items?: BookmarkListResponse[];
  hasMore?: boolean;
}
