/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface BookmarkListResponse {
  videoId?: string;
  title?: string;
  thumbnailUrl?: string;
  viewCount?: number;
  uploaderName?: string;
  watchProgressPercent?: number;
  duration?: number;
  uploadDate?: string;
}
