/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { BookmarkPlaylistResponse } from "./bookmarkPlaylistResponse";

export interface BookmarkSummaryResponse {
  shortForm?: BookmarkPlaylistResponse;
  longForm?: BookmarkPlaylistResponse;
}
