/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { CommentItemResponse } from "./commentItemResponse";

export interface CommentPageResponse {
  comments?: CommentItemResponse[];
  hasMore?: boolean;
  myComment?: CommentItemResponse;
}
