/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type ContentUpdateRequestVisibility = typeof ContentUpdateRequestVisibility[keyof typeof ContentUpdateRequestVisibility];


export const ContentUpdateRequestVisibility = {
  PRIVATE: 'PRIVATE',
  PUBLIC: 'PUBLIC',
} as const;
