/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ContentUpdateRequestVisibility } from "./contentUpdateRequestVisibility";

export interface ContentUpdateRequest {
  title?: string;
  description?: string;
  visibility?: ContentUpdateRequestVisibility;
  tagIds?: number[];
}
