/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface CreateUserRequest {
  email: string;
  /**
   * @minLength 8
   * @maxLength 20
   */
  password: string;
  /**
   * @minLength 2
   * @maxLength 20
   */
  nickname: string;
  profileImageUrl?: string;
}
