/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { FieldError } from './fieldError';

export interface ErrorMessage {
  code?: string;
  message?: string;
  errors?: FieldError[];
}
