/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type GetBookmarkListVideoType = typeof GetBookmarkListVideoType[keyof typeof GetBookmarkListVideoType];


export const GetBookmarkListVideoType = {
  SHORT: 'SHORT',
  LONG: 'LONG',
} as const;
