/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type GetBookmarkRankingParams = {
  /**
   * 조회할 랭킹 개수 (기본값: 10, 최대 노출 개수 지정)
   */
  limit?: number;
};
