/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { GetBookmarkListVideoType } from "./getBookmarkListVideoType";

export type GetBookmarkListParams = {
  videoType: GetBookmarkListVideoType;
  page?: number;
  size?: number;
};
