/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type GetContentsDirection =
  (typeof GetContentsDirection)[keyof typeof GetContentsDirection];

export const GetContentsDirection = {
  ASC: "ASC",
  DESC: "DESC",
} as const;
