/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { GetContentsDirection } from './getContentsDirection';

export type GetContentsParams = {
keyword?: string;
page?: number;
size?: number;
sortBy?: string;
direction?: GetContentsDirection;
};
