/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type GetFeedParams = {
  /**
   * 페이지 번호 (0부터 시작)
   * @minimum 0
   */
  page?: number;
  /**
   * 한 페이지당 가져올 비디오 개수
   * @minimum 1
   * @maximum 50
   */
  size?: number;
};
