/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PointTransactionHistoryRequest } from "./pointTransactionHistoryRequest";

export type GetMyPointTransactionHistoryParams = {
  req: PointTransactionHistoryRequest;
};
