/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type GetMyContentsDirection = typeof GetMyContentsDirection[keyof typeof GetMyContentsDirection];


export const GetMyContentsDirection = {
  ASC: 'ASC',
  DESC: 'DESC',
} as const;
