/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type GetUsersDirection =
  (typeof GetUsersDirection)[keyof typeof GetUsersDirection];

export const GetUsersDirection = {
  ASC: "ASC",
  DESC: "DESC",
} as const;
