/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type GetUsersUserRole =
  (typeof GetUsersUserRole)[keyof typeof GetUsersUserRole];

export const GetUsersUserRole = {
  VIEWER: "VIEWER",
  UPLOADER: "UPLOADER",
  ADMIN: "ADMIN",
} as const;
