/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { GetUsersDirection } from './getUsersDirection';
import type { GetUsersUserRole } from './getUsersUserRole';

export type GetUsersParams = {
userRole: GetUsersUserRole;
keyword?: string;
page?: number;
size?: number;
sortBy?: string;
direction?: GetUsersDirection;
};
