/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type GetVerticalFeedParams = {
/**
 * 가져올 개수 (기본 10)
 * @minimum 1
 * @maximum 50
 */
size?: number;
};
