/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type KakaoLoginParams = {
/**
 * 카카오 인가코드
 */
code: string;
/**
 * CSRF 방지용 state 토큰
 */
state?: string;
};
