/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type LoginResponseRole = typeof LoginResponseRole[keyof typeof LoginResponseRole];


export const LoginResponseRole = {
  VIEWER: 'VIEWER',
  UPLOADER: 'UPLOADER',
  ADMIN: 'ADMIN',
} as const;
