/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { LoginResponseRole } from "./loginResponseRole";

export interface LoginResponse {
  userId?: number;
  email?: string;
  nickname?: string;
  profileImageUrl?: string;
  role?: LoginResponseRole;
  accessToken?: string;
  refreshToken?: string;
  isNewUser?: boolean;
  onboardingCompleted?: boolean;
}
