/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PresignedPart } from "./presignedPart";

export interface MultipartInitResponse {
  videoId?: string;
  objectKey?: string;
  uploadId?: string;
  partSizeBytes?: number;
  presignedParts?: PresignedPart[];
  expiresAtEpochSeconds?: number;
}
