/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { CompletedPartDto } from "./completedPartDto";

export interface MultipartCompleteRequest {
  uploadId?: string;
  parts?: CompletedPartDto[];
  sizeBytes?: number;
}
