/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { AdminContentResponse } from "./adminContentResponse";

export interface PageResponseAdminContentResponse {
  content?: AdminContentResponse[];
  page?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
}
