/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { UploaderContentResponse } from "./uploaderContentResponse";

export interface PageResponseUploaderContentResponse {
  content?: UploaderContentResponse[];
  page?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
}
