/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { AdminUserResponse } from './adminUserResponse';

export interface PageResponseAdminUserResponse {
  content?: AdminUserResponse[];
  page?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
}
