/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PageableObject } from './pageableObject';
import type { SortObject } from './sortObject';
import type { VideoSearchResponse } from './videoSearchResponse';

export interface PageVideoSearchResponse {
  totalPages?: number;
  totalElements?: number;
  first?: boolean;
  last?: boolean;
  pageable?: PageableObject;
  size?: number;
  content?: VideoSearchResponse[];
  number?: number;
  sort?: SortObject;
  numberOfElements?: number;
  empty?: boolean;
}
