/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface PointTransactionHistoryRequest {
  /** 조회 시작일 */
  startDate?: string;
  /** 조회 종료일 */
  endDate?: string;
}
