/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type PointPolicyResponsePolicyName = typeof PointPolicyResponsePolicyName[keyof typeof PointPolicyResponsePolicyName];


export const PointPolicyResponsePolicyName = {
  AD_REWARD: 'AD_REWARD',
  PURCHASE_RATE: 'PURCHASE_RATE',
  DAILY_AD_LIMIT: 'DAILY_AD_LIMIT',
} as const;
