/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PointPolicyResponsePolicyName } from "./pointPolicyResponsePolicyName";

export interface PointPolicyResponse {
  policyName?: PointPolicyResponsePolicyName;
  description?: string;
  policyValue?: number;
}
