/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PointPolicyUpdateRequestPolicyName } from "./pointPolicyUpdateRequestPolicyName";

export interface PointPolicyUpdateRequest {
  policyName?: PointPolicyUpdateRequestPolicyName;
  policyValue?: number;
}
