/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PointTransactionHistoryResponseType } from "./pointTransactionHistoryResponseType";

export interface PointTransactionHistoryResponse {
  transactionId?: number;
  amount?: number;
  type?: PointTransactionHistoryResponseType;
  balanceAfterTransaction?: number;
  createdAt?: string;
}
