/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { SubscriptionResponse } from "./subscriptionResponse";

export interface RegisterResponse {
  registered?: boolean;
  message?: string;
  subscription?: SubscriptionResponse;
}
