/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface RegisterRequest {
  /** @pattern ^01[016789]-?\d{3,4}-?\d{4}$ */
  phoneNumber: string;
}
