/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { SearchVideosVideoType } from './searchVideosVideoType';

export type SearchVideosParams = {
keyword?: string;
videoType?: SearchVideosVideoType;
tag?: string;
page?: number;
size?: number;
};
