/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type SearchVideosVideoType =
  (typeof SearchVideosVideoType)[keyof typeof SearchVideosVideoType];

export const SearchVideosVideoType = {
  SHORT: "SHORT",
  LONG: "LONG",
} as const;
