/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { VideoFeedResponseDto } from './videoFeedResponseDto';

export interface SliceResponseVideoFeedResponseDto {
  content?: VideoFeedResponseDto[];
  currentPage?: number;
  size?: number;
  hasNext?: boolean;
}
