/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface SortObject {
  sorted?: boolean;
  empty?: boolean;
  unsorted?: boolean;
}
