/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface SubscriptionResponse {
  maskedPhoneNumber?: string;
  plan?: string;
  planDisplayName?: string;
  monthlyFee?: number;
  active?: boolean;
}
