/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface TagVideoResponse {
  videoId?: string;
  title?: string;
  thumbnailUrl?: string;
  viewCount?: number;
  uploaderName?: string;
  watchProgressPercent?: number;
  uploadedAt?: string;
  duration?: number;
}
