/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface UpdateUserRequest {
  /**
   * @minLength 2
   * @maxLength 20
   */
  nickname?: string;
  /**
   * @minLength 8
   * @maxLength 20
   */
  password?: string;
  profileImageUrl?: string;
  preferredTagIds?: number[];
}
