/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type UploadRequestVisibility =
  (typeof UploadRequestVisibility)[keyof typeof UploadRequestVisibility];

export const UploadRequestVisibility = {
  PRIVATE: "PRIVATE",
  PUBLIC: "PUBLIC",
} as const;
