/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type UploaderContentResponseVisibility =
  (typeof UploaderContentResponseVisibility)[keyof typeof UploaderContentResponseVisibility];

export const UploaderContentResponseVisibility = {
  PRIVATE: "PRIVATE",
  PUBLIC: "PUBLIC",
} as const;
