/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { UploaderContentResponseVisibility } from "./uploaderContentResponseVisibility";

export interface UploaderContentResponse {
  videoId?: string;
  thumbnailUrl?: string;
  title?: string;
  description?: string;
  otherVideoUrl?: string;
  viewCount?: number;
  likeCount?: number;
  dislikeCount?: number;
  commentCount?: number;
  visibility?: UploaderContentResponseVisibility;
  createdAt?: string;
}
