/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { UploadRequestVideoType } from "./uploadRequestVideoType";
import type { UploadRequestVisibility } from "./uploadRequestVisibility";

export interface UploadRequest {
  title?: string;
  description?: string;
  videoType?: UploadRequestVideoType;
  otherVideoUrl?: string;
  tagIds?: number[];
  visibility?: UploadRequestVisibility;
}
