/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type UploadRequestVideoType =
  (typeof UploadRequestVideoType)[keyof typeof UploadRequestVideoType];

export const UploadRequestVideoType = {
  SHORT: "SHORT",
  LONG: "LONG",
} as const;
