/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { UserDetailResponseBanned } from './userDetailResponseBanned';
import type { UserDetailResponseRole } from './userDetailResponseRole';

export interface UserDetailResponse {
  userId?: number;
  email?: string;
  nickname?: string;
  profileImageUrl?: string;
  role?: UserDetailResponseRole;
  oauthProvider?: string;
  oauthId?: string;
  banned?: UserDetailResponseBanned;
  bannedUntil?: string;
  banReason?: string;
  bannedAt?: string;
  createdAt?: string;
  updatedAt?: string;
}
