/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { UserStatusUpdateRequestBanStatus } from './userStatusUpdateRequestBanStatus';

export interface UserStatusUpdateRequest {
  userIds?: number[];
  banStatus?: UserStatusUpdateRequestBanStatus;
  banReason?: string;
}
