/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type UserDetailResponseRole = typeof UserDetailResponseRole[keyof typeof UserDetailResponseRole];


export const UserDetailResponseRole = {
  VIEWER: 'VIEWER',
  UPLOADER: 'UPLOADER',
  ADMIN: 'ADMIN',
} as const;
