/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { UserResponseBanned } from "./userResponseBanned";
import type { UserResponseRole } from "./userResponseRole";

export interface UserResponse {
  userId?: number;
  email?: string;
  nickname?: string;
  profileImageUrl?: string;
  role?: UserResponseRole;
  banned?: UserResponseBanned;
  createdAt?: string;
}
