/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type VideoInfoResponseVisibility =
  (typeof VideoInfoResponseVisibility)[keyof typeof VideoInfoResponseVisibility];

export const VideoInfoResponseVisibility = {
  PRIVATE: "PRIVATE",
  PUBLIC: "PUBLIC",
} as const;
