/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type VideoFeedResponseDtoVideoType =
  (typeof VideoFeedResponseDtoVideoType)[keyof typeof VideoFeedResponseDtoVideoType];

export const VideoFeedResponseDtoVideoType = {
  SHORT: "SHORT",
  LONG: "LONG",
} as const;
