/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { VideoFeedResponseDtoVideoType } from './videoFeedResponseDtoVideoType';

export interface VideoFeedResponseDto {
  videoId?: number;
  userId?: number;
  uploaderNickname?: string;
  uploaderProfileImageUrl?: string;
  title?: string;
  description?: string;
  thumbnailUrl?: string;
  duration?: number;
  tags?: string[];
  viewCount?: number;
  likeCount?: number;
  uploadDate?: string;
  videoType?: VideoFeedResponseDtoVideoType;
  watchProgress?: number;
}
