/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { UploadRequest } from './uploadRequest';

export interface VideoUploadMultipart {
  /** 썸네일 이미지 파일 */
  image?: Blob;
  /** 업로드 메타데이터(JSON) */
  data?: UploadRequest;
}
