/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { VideoInfoResponseVisibility } from "./videoInfoResponseVisibility";
import type { WatchHistoryResponse } from "./watchHistoryResponse";

export interface VideoInfoResponse {
  videoId?: string;
  title?: string;
  description?: string;
  thumbnailUrl?: string;
  visibility?: VideoInfoResponseVisibility;
  tagIds?: string[];
  createdAt?: string;
  otherVideoUrl?: string;
  userProfile?: string;
  userNickname?: string;
  watchHistory?: WatchHistoryResponse;
}
