/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface VideoSearchResponse {
  videoId?: number;
  title?: string;
  thumbnailUrl?: string;
  viewCount?: number;
  duration?: number;
  createdAt?: string;
}
